const GAME_DATA={questions:[
 {text:'Your crush watches your story in two minutes.',a:{text:'They were simply online',points:0},b:{text:'They were waiting for my update',points:2}},
 {text:'They reply “hahaha” with one extra “ha.”',a:{text:'It is still just laughter',points:0},b:{text:'Flirting. The extra “ha” confirms it',points:2}},
 {text:'You both post the same song this week.',a:{text:'Popular song, normal coincidence',points:0},b:{text:'Our secret soundtrack has begun',points:2}},
 {text:'They borrow your pen and keep it.',a:{text:'They forgot to return it',points:0},b:{text:'A souvenir from our first chapter',points:2}},
 {text:'They send “ingat” before you go home.',a:{text:'A kind, normal message',points:0},b:{text:'Practically a soft launch',points:2}},
 {text:'Their friend suddenly follows you.',a:{text:'The algorithm did its thing',points:0},b:{text:'The investigation team knows about me',points:2}},
 {text:'Your eyes meet across the classroom.',a:{text:'We happened to look up',points:0},b:{text:'That was a full conversation',points:2}},
 {text:'They react ❤️ to your message.',a:{text:'A convenient reaction button',points:0},b:{text:'I should start planning our anniversary',points:2}}
],results:[
 {max:1,slug:'certified-realist',title:'Certified Realist',emoji:'🧊',percent:12,description:'Receipts first. Butterflies later.',traits:['Evidence required','Calm replies','Plot-resistant'],tag:'TAG YOUR REALITY-CHECK FRIEND'},
 {max:4,slug:'soft-launch-dreamer',title:'Soft-Launch Dreamer',emoji:'🌤️',percent:34,description:'Tiny kilig. Feet still on the ground.',traits:['Hopeful','Grounded','Screenshots saved'],tag:'TAG YOUR SOFT-LAUNCH PARTNER'},
 {max:7,slug:'kilig-investigator',title:'Kilig Investigator',emoji:'🔎',percent:58,description:'Every “haha” becomes fresh evidence.',traits:['Clue collector','Chat analyst','Case open'],tag:'TAG YOUR FELLOW INVESTIGATOR'},
 {max:10,slug:'romcom-screenwriter',title:'Rom-Com Screenwriter',emoji:'🎬',percent:76,description:'One eye contact = a whole love story.',traits:['Fast imagination','Main-character','Own soundtrack'],tag:'TAG YOUR ROM-COM CO-WRITER'},
 {max:13,slug:'delulu-director',title:'Delulu Director',emoji:'🎥',percent:91,description:'You provide the signs, lighting, and soundtrack.',traits:['Plot producer','Sign specialist','Kilig editor'],tag:'TAG YOUR ASSISTANT DIRECTOR'},
 {max:16,slug:'delulu-ceo',title:'Delulu CEO',emoji:'👑',percent:99,description:'Evidence optional. Imagination profitable.',traits:['Chief dreamer','Owns the plot','Zero boring moments'],tag:'TAG YOUR DELULU BUSINESS PARTNER'}
]};
const GAME_URL='https://hiclassmate.com/games/how-delulu-are-you/';const $=s=>document.querySelector(s);const el={start:$('#start-panel'),question:$('#question-panel'),result:$('#result-panel'),startButton:$('#start-button'),shareStart:$('#share-start-button'),questionText:$('#question-text'),a:$('#choice-a'),b:$('#choice-b'),progressLabel:$('#progress-label'),progressCount:$('#progress-count'),progressBar:$('#progress-bar'),emoji:$('#result-emoji'),title:$('#result-title'),percent:$('#result-percent'),description:$('#result-description'),traits:$('#trait-list'),tag:$('#tag-prompt'),shareGame:$('#share-game-button'),shareResult:$('#share-result-button'),restart:$('#restart-button')};let questionIndex=0,score=0,currentResult=null;function track(n,p={}){window.hcTrack?.(n,p)}function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){questionIndex=0;score=0;currentResult=null;document.body.dataset.screen='start';el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Reality check ready?';el.progressCount.textContent='6 possible ranks';el.progressBar.style.width='0%'}function start(){track('game_start',{question_count:8});el.start.hidden=true;showQuestion()}function showQuestion(){document.body.dataset.screen='question';const q=GAME_DATA.questions[questionIndex];el.question.hidden=false;el.questionText.textContent=q.text;el.a.querySelector('strong').textContent=q.a.text;el.b.querySelector('strong').textContent=q.b.text;el.progressLabel.textContent=`Situation ${questionIndex+1} of 8`;el.progressCount.textContent=`${Math.round(questionIndex/8*100)}%`;el.progressBar.style.width=`${questionIndex/8*100}%`;el.a.onclick=()=>choose(q.a,'real_talk');el.b.onclick=()=>choose(q.b,'delulu_mode')}function choose(answer,choice){score+=answer.points;track('question_answer',{question_number:questionIndex+1,answer_choice:choice,answer_points:answer.points});questionIndex++;questionIndex===8?finish():showQuestion()}
function finish(){document.body.dataset.screen='result';currentResult=GAME_DATA.results.find(result=>score<=result.max);el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Case closed';el.progressCount.textContent=`${score}/16 delulu points`;el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`${currentResult.percent}%`;el.description.textContent=currentResult.description;el.traits.replaceChildren(...currentResult.traits.map(t=>{const chip=document.createElement('span');chip.textContent=t;return chip}));el.tag.textContent=currentResult.tag;track('game_complete',{score,result_type:currentResult.slug,result_percent:currentResult.percent,question_count:8});track('result_view',{score,result_type:currentResult.slug,result_percent:currentResult.percent})}function shareGame(){track('share_game',{platform:'facebook'});openFacebook(GAME_URL,'Real talk or delulu mode? Take this 8-question Pinoy crush test!')}function shareResult(){if(!currentResult)return;track('share_result',{platform:'facebook',result_type:currentResult.slug,score});openFacebook(`${GAME_URL}results/${currentResult.slug}/?score=${score}`,`I got ${currentResult.title}! How delulu are you?`)}el.startButton.onclick=start;el.shareStart.onclick=shareGame;el.shareGame.onclick=shareGame;el.shareResult.onclick=shareResult;el.restart.onclick=()=>{track('replay',{result_type:currentResult?.slug||'unknown'});reset()};reset();
