const GAME_DATA={results:{
belter:{slug:'biriterang-walang-preno',title:'Biriterang Walang Preno',emoji:'🔥',comparison:'more likely to attempt the impossible high note',basePercent:91,description:'The key is too high, the neighbors are awake, and none of that matters. You attack every chorus like it is the grand finals.',traits:['High-note hunter','Zero fear','Applause collector']},
hugot:{slug:'hugot-ballad-ceo',title:'Hugot Ballad CEO',emoji:'💔',comparison:'more emotionally invested in every lyric',basePercent:93,description:'One sad intro plays and suddenly the room is your teleserye finale. You do not sing the song—you relive it.',traits:['May pinaghuhugutan','Window-stare expert','Feels every word']},
duet:{slug:'duet-recruiter',title:'The Duet Recruiter',emoji:'🤝',comparison:'more likely to pull a friend onto the stage',basePercent:88,description:'You never let anyone sing alone, mostly because you already assigned their harmony. Your favorite sentence is “Sabay tayo!”',traits:['Barkada magnet','Harmony negotiator','No friend left seated']},
hoarder:{slug:'microphone-hoarder',title:'Certified Microphone Hoarder',emoji:'🎤',comparison:'less likely to surrender the microphone',basePercent:95,description:'You said “one song lang” six songs ago. The queue is now your personal concert setlist and everyone has accepted it.',traits:['Permanent mic custody','Encore specialist','Queue controller']},
shy:{slug:'shy-until-the-chorus',title:'Shy Until the Chorus',emoji:'😳',comparison:'more likely to transform after the first verse',basePercent:86,description:'At first you hide behind the snacks. Then the chorus arrives and suddenly you know the lyrics, choreography, and backup vocals.',traits:['Secret performer','Chorus activated','Surprise main character']},
dance:{slug:'dance-break-director',title:'Dance Break Director',emoji:'🪩',comparison:'more likely to turn one song into a full production',basePercent:90,description:'Why stand still when the living room is a stage? You provide choreography, backup dancers, and unsolicited camera direction.',traits:['Living-room choreographer','Energy supplier','Born for the bridge']},
inventor:{slug:'lyrics-inventor',title:'The Lyrics Inventor',emoji:'📝',comparison:'more confident while singing completely new words',basePercent:94,description:'You may not know the lyrics, but confidence fills every blank. Even the videoke machine starts questioning its own subtitles.',traits:['Confident mumbling','Ad-lib genius','Never stops mid-song']},
request:{slug:'titas-request-specialist',title:"Tita's Request Specialist",emoji:'👑',comparison:'more trusted with the family songbook',basePercent:89,description:'Someone asks for an old favorite and you already know the number. You keep the reunion happy and earn extra food afterward.',traits:['Songbook memory','Family favorite','Merienda reward unlocked']}
},questions:[
{text:'The microphone reaches you. What happens?',a:{text:'Stand up. This needs full power.',scores:{belter:3,dance:1}},b:{text:'Pull a friend in for a duet.',scores:{duet:3,shy:1}}},
{text:'Your song choice is...',a:{text:'A painful ballad with maximum hugot',scores:{hugot:3,request:1}},b:{text:'A crowd anthem everyone can shout',scores:{dance:2,duet:2}}},
{text:'You forget the next line.',a:{text:'Invent words with confidence',scores:{inventor:3,hoarder:1}},b:{text:'Point the mic at the barkada',scores:{duet:3,shy:1}}},
{text:'Someone says “last song na.”',a:{text:'Correct. My last three songs.',scores:{hoarder:3,belter:1}},b:{text:'Make it a giant group finale',scores:{dance:2,duet:2}}},
{text:'The impossible high note arrives.',a:{text:'Commit. Bahala na si Batman.',scores:{belter:3,inventor:1}},b:{text:'Turn it into emotional acting',scores:{hugot:3,shy:1}}},
{text:'A tita requests an old classic.',a:{text:'Already typing the song number',scores:{request:3,hugot:1}},b:{text:'Ask her to sing it with you',scores:{duet:2,request:2}}},
{text:'Your friend secretly records you.',a:{text:'Find the camera and perform harder',scores:{dance:3,hoarder:1}},b:{text:'Hide—then nail the chorus anyway',scores:{shy:3,belter:1}}},
{text:'Pick your videoke superpower.',a:{text:'Know every lyric ever written',scores:{request:2,hugot:2}},b:{text:'Make wrong lyrics sound correct',scores:{inventor:3,hoarder:1}}}
]};
const el={start:document.querySelector('#start-panel'),question:document.querySelector('#question-panel'),result:document.querySelector('#result-panel'),startButton:document.querySelector('#start-button'),shareStart:document.querySelector('#share-start-button'),questionText:document.querySelector('#question-text'),a:document.querySelector('#choice-a'),b:document.querySelector('#choice-b'),progressLabel:document.querySelector('#progress-label'),progressCount:document.querySelector('#progress-count'),progressBar:document.querySelector('#progress-bar'),emoji:document.querySelector('#result-emoji'),title:document.querySelector('#result-title'),percent:document.querySelector('#result-percent'),description:document.querySelector('#result-description'),traits:document.querySelector('#trait-list'),shareGame:document.querySelector('#share-game-button'),shareResult:document.querySelector('#share-result-button'),restart:document.querySelector('#restart-button')};
let index=0,scores={},currentResult=null,currentPercent=0;const GAME_URL='https://hiclassmate.com/games/videoke-persona/';
function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){index=0;scores=Object.fromEntries(Object.keys(GAME_DATA.results).map(key=>[key,0]));currentResult=null;currentPercent=0;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Mic check!';el.progressCount.textContent='8 iconic results';el.progressBar.style.width='0%'}
function track(eventName,params={}){if(typeof window.hcTrack==='function')window.hcTrack(eventName,params)}
function start(){track('quiz_start');el.start.hidden=true;showQuestion()}
function showQuestion(){const q=GAME_DATA.questions[index];el.question.hidden=false;el.questionText.textContent=q.text;el.a.querySelector('strong').textContent=q.a.text;el.b.querySelector('strong').textContent=q.b.text;el.progressLabel.textContent=`Song ${index+1} of 8`;el.progressCount.textContent=`${Math.round(index/8*100)}%`;el.progressBar.style.width=`${index/8*100}%`;el.a.onclick=()=>choose(q.a,'a');el.b.onclick=()=>choose(q.b,'b')}
function choose(answer,answerChoice){track('question_answer',{question_number:index+1,answer_choice:answerChoice});Object.entries(answer.scores).forEach(([key,value])=>scores[key]+=value);index+=1;if(index===GAME_DATA.questions.length)showResult();else showQuestion()}
function showResult(){const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);currentResult=GAME_DATA.results[ranked[0][0]];currentPercent=Math.min(98,currentResult.basePercent+Math.max(0,ranked[0][1]-7));el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Persona unlocked';el.progressCount.textContent='1 of 8 personas';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`You are ${currentResult.comparison} than ${currentPercent}% of players`;el.description.textContent=currentResult.description;el.traits.innerHTML=currentResult.traits.map(trait=>`<span>${trait}</span>`).join('');const resultData={result_type:currentResult.slug,result_percent:currentPercent,question_count:GAME_DATA.questions.length};track('quiz_complete',resultData);track('result_view',resultData)}
function shareGame(){track('facebook_share_click',{share_type:'game'});openFacebook(GAME_URL,"What's your videoke persona? Make 8 quick choices and expose your karaoke alter ego!")}
function shareResult(){if(!currentResult)return;track('facebook_share_click',{share_type:'result',result_type:currentResult.slug,result_percent:currentPercent});const resultUrl=`${GAME_URL}results/${currentResult.slug}/?score=${currentPercent}`;openFacebook(resultUrl,`I got ${currentResult.title}! Apparently I am ${currentResult.comparison} than ${currentPercent}% of players. Ikaw, sino ka sa videoke night?`)}
el.startButton.addEventListener('click',start);el.shareStart.addEventListener('click',shareGame);el.shareGame.addEventListener('click',shareGame);el.shareResult.addEventListener('click',shareResult);el.restart.addEventListener('click',()=>{track('retry_click',{result_type:currentResult?.slug||'unknown'});reset()});document.querySelectorAll('a[href="/"]').forEach(link=>link.addEventListener('click',()=>track('next_game_click',{destination:'home'})));reset();
