const GAME_DATA={questions:[
 {text:'The jeepney is almost full. Where do you sit?',a:{text:'Window seat, headphones on',type:'chill'},b:{text:'Near the exit—ready for anything',type:'ready'}},
 {text:'Traffic has not moved for ten minutes.',a:{text:'Playlist on. I accept my fate',type:'chill'},b:{text:'I already found Plan B',type:'ready'}},
 {text:'Someone passes their fare down the row.',a:{text:'I pass it quietly',type:'quiet'},b:{text:'I become the fare coordinator',type:'helper'}},
 {text:'It starts raining halfway home.',a:{text:'I brought an umbrella and extras',type:'prepared'},b:{text:'Takbo! Adventure mode activated',type:'chaos'}},
 {text:'Your friend is late to the meetup.',a:{text:'I save them a seat',type:'helper'},b:{text:'I send live traffic updates',type:'navigator'}},
 {text:'You need to say “Para po!”',a:{text:'Soft voice, then hope for the best',type:'quiet'},b:{text:'Clear, confident, heard by everyone',type:'captain'}},
 {text:'A faster route suddenly appears.',a:{text:'Stick to the route I know',type:'prepared'},b:{text:'Shortcut unlocked—follow me',type:'navigator'}},
 {text:'Your whole barkada commutes together.',a:{text:'I keep everyone together',type:'captain'},b:{text:'I turn the ride into a comedy show',type:'chaos'}}
],results:{
 chill:{slug:'window-seat-dreamer',title:'Window-Seat Dreamer',emoji:'🎧',percent:72,description:'Traffic outside. Main-character soundtrack inside.',traits:['Playlist ready','Calm energy','Cloud watcher'],tag:'TAG YOUR WINDOW-SEAT TWIN'},
 ready:{slug:'door-ready-sprinter',title:'Door-Ready Sprinter',emoji:'🏃',percent:81,description:'One hand on the rail. One eye on the exit.',traits:['Fast moves','Exit expert','Zero delay'],tag:'TAG THE FRIEND WHO IS ALWAYS READY'},
 quiet:{slug:'silent-para-po',title:'Silent “Para Po”',emoji:'🤫',percent:64,description:'Your voice is soft, but your commute lore is strong.',traits:['Low-key','Polite pro','Brave eventually'],tag:'TAG YOUR QUIET COMMUTE BUDDY'},
 helper:{slug:'bayanihan-commuter',title:'Bayanihan Commuter',emoji:'🤝',percent:88,description:'Fares, seats, directions—you keep the whole ride moving.',traits:['Fare passer','Seat saver','Human help desk'],tag:'TAG THE BARKADA HELPER'},
 prepared:{slug:'umbrella-commander',title:'Umbrella Commander',emoji:'☂️',percent:93,description:'Rain, traffic, low battery—you packed the solution.',traits:['Always ready','Backup plan','Weatherproof'],tag:'TAG THE FRIEND WITH EVERYTHING'},
 chaos:{slug:'commute-chaos-legend',title:'Commute Chaos Legend',emoji:'🌪️',percent:97,description:'Every delayed ride becomes tomorrow’s funniest story.',traits:['Plot magnet','Laughs first','Adventure mode'],tag:'TAG YOUR CHAOS CO-PILOT'},
 navigator:{slug:'shortcut-gps',title:'Shortcut GPS',emoji:'🗺️',percent:91,description:'You know three routes, two shortcuts, and one secret terminal.',traits:['Route genius','Plan B ready','ETA prophet'],tag:'TAG YOUR HUMAN GOOGLE MAPS'},
 captain:{slug:'barkada-ride-captain',title:'Barkada Ride Captain',emoji:'🚌',percent:95,description:'Nobody gets left behind when you lead the commute.',traits:['Head counter','Loud para po','Group guardian'],tag:'TAG YOUR RIDE CAPTAIN'}
}};
const GAME_URL='https://hiclassmate.com/games/pinoy-commute-persona/';const $=s=>document.querySelector(s);const el={start:$('#start-panel'),question:$('#question-panel'),result:$('#result-panel'),startButton:$('#start-button'),shareStart:$('#share-start-button'),questionText:$('#question-text'),a:$('#choice-a'),b:$('#choice-b'),progressLabel:$('#progress-label'),progressCount:$('#progress-count'),progressBar:$('#progress-bar'),emoji:$('#result-emoji'),title:$('#result-title'),percent:$('#result-percent'),description:$('#result-description'),traits:$('#trait-list'),tag:$('#tag-prompt'),shareGame:$('#share-game-button'),shareResult:$('#share-result-button'),restart:$('#restart-button')};let questionIndex=0,scores={},choiceSignature=0,currentResult=null;function track(n,p={}){window.hcTrack?.(n,p)}function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){questionIndex=0;scores=Object.fromEntries(Object.keys(GAME_DATA.results).map(k=>[k,0]));choiceSignature=0;currentResult=null;document.body.dataset.screen='start';el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Next stop: your persona';el.progressCount.textContent='8 possible rides';el.progressBar.style.width='0%'}function start(){track('game_start',{question_count:8});el.start.hidden=true;showQuestion()}function showQuestion(){document.body.dataset.screen='question';const q=GAME_DATA.questions[questionIndex];el.question.hidden=false;el.questionText.textContent=q.text;el.a.querySelector('strong').textContent=q.a.text;el.b.querySelector('strong').textContent=q.b.text;el.progressLabel.textContent=`Stop ${questionIndex+1} of 8`;el.progressCount.textContent=`${Math.round(questionIndex/8*100)}%`;el.progressBar.style.width=`${questionIndex/8*100}%`;el.a.onclick=()=>choose(q.a,'a');el.b.onclick=()=>choose(q.b,'b')}function choose(answer,choice){scores[answer.type]++;choiceSignature=choiceSignature*2+(choice==='b'?1:0);track('question_answer',{question_number:questionIndex+1,answer_choice:choice,answer_type:answer.type});questionIndex++;questionIndex===8?finish():showQuestion()}
function finish(){document.body.dataset.screen='result';const max=Math.max(...Object.values(scores));const tied=Object.keys(GAME_DATA.results).filter(key=>scores[key]===max);const winner=tied[choiceSignature%tied.length];currentResult=GAME_DATA.results[winner];el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Destination reached';el.progressCount.textContent='Persona unlocked';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`${currentResult.percent}%`;el.description.textContent=currentResult.description;el.traits.replaceChildren(...currentResult.traits.map(t=>{const chip=document.createElement('span');chip.textContent=t;return chip}));el.tag.textContent=currentResult.tag;track('game_complete',{result_type:currentResult.slug,result_percent:currentResult.percent,question_count:8});track('result_view',{result_type:currentResult.slug,result_percent:currentResult.percent})}function shareGame(){track('share_game',{platform:'facebook'});openFacebook(GAME_URL,'Window seat or door ready? Find your Pinoy commute persona!')}function shareResult(){if(!currentResult)return;track('share_result',{platform:'facebook',result_type:currentResult.slug});openFacebook(`${GAME_URL}results/${currentResult.slug}/`,`I got ${currentResult.title}! What is your Pinoy commute persona?`)}el.startButton.onclick=start;el.shareStart.onclick=shareGame;el.shareGame.onclick=shareGame;el.shareResult.onclick=shareResult;el.restart.onclick=()=>{track('replay',{result_type:currentResult?.slug||'unknown'});reset()};reset();
