(()=>{
  'use strict';
  const data=MIRROR_DATA,url='https://hiclassmate.com/games/date-yourself/',$=id=>document.getElementById(id);
  let choices=[],index=0,screen='start',current=null,profile=null,accepting=true,timer;
  const track=(event,details={})=>window.hcTrack?.(event,{quiz_id:data.id,game_id:data.id,...details});
  function show(next){screen=next;document.body.dataset.screen=next;['start','question','profile','result'].forEach(key=>$(key+'-panel').hidden=key!==next);window.scrollTo({top:0,behavior:'instant'})}
  function progress(n,label){$('progress-label').textContent=label;$('progress-count').textContent=n+' / 8';$('progress-bar').style.width=n/8*100+'%';$('progress-track').setAttribute('aria-valuenow',n);$('progress-track').setAttribute('aria-valuetext',label)}
  function lock(){accepting=false;clearTimeout(timer);timer=setTimeout(()=>{accepting=true},300)}
  function question(){const topic=data.topics[Math.floor(index/2)],giving=index%2===0;show('question');progress(index,'Question '+(index+1)+' of 8');$('question-kicker').textContent=giving?'YOUR USUAL MOVE':'WHAT YOU LIKE RECEIVING';$('question-text').textContent=giving?topic.give:topic.want;$('back-button').disabled=index===0;
    $('answers').replaceChildren(...(giving?topic.actions:topic.preferences).map((answer,i)=>{const button=document.createElement('button');button.type='button';button.className='answer';button.dataset.choice=i;const letter=Object.assign(document.createElement('span'),{textContent:'ABC'[i],className:'answer-letter'});letter.setAttribute('aria-hidden','true');button.append(letter,Object.assign(document.createElement('strong'),{textContent:answer.text}));button.onclick=event=>{if(!accepting||screen!=='question'||event.detail>1)return;lock();choices[index]=i;track('question_answer',{question_id:topic.id+'_'+(giving?'give':'want'),question_number:index+1,answer_choice:'abc'[i]});index++;index===8?meet():question()};return button}));$('question-text').focus({preventScroll:true})}
  function meet(){profile=MirrorEngine.profile(data,choices);show('profile');progress(8,'Your match is ready');$('profile-facts').replaceChildren(...profile.rows.map(row=>{const li=document.createElement('li');li.dataset.topic=row.topic;li.append(Object.assign(document.createElement('span'),{textContent:row.name}),Object.assign(document.createElement('strong'),{textContent:row.action.profile}));return li}));$('profile-heading').focus({preventScroll:true});track('profile_view',{question_count:8})}
  function reveal(verdict,event){if(screen!=='profile'||!accepting||event.detail>1)return;lock();current=MirrorEngine.result(data,choices,verdict);const r=current.result;document.documentElement.style.setProperty('--result-color',r.color);$('result-symbol').textContent=r.symbol;$('result-title').textContent=r.title;$('result-verdict').textContent=r.verdict;$('result-match').textContent=current.aligned+' / 4';$('result-truth').textContent=r.truth;$('result-gift').textContent=current.gift.action.gift;$('result-friction').textContent=current.friction.action.friction;
    $('evidence-rows').replaceChildren(...current.rows.map(row=>{const li=document.createElement('li');li.append(Object.assign(document.createElement('b'),{textContent:row.name+' · '+(row.aligned?'ALIGNED':'DIFFERENT')}),Object.assign(document.createElement('span'),{textContent:'You give: '+row.action.short}),Object.assign(document.createElement('span'),{textContent:'You want: '+row.preference.short}));return li}));$('evidence').open=false;show('result');progress(8,'That person was you.');$('reveal-heading').focus({preventScroll:true});track('date_decision',{decision:verdict});track('game_complete',{result_type:r.slug,decision:verdict,aligned_count:current.aligned});track('result_view',{result_type:r.slug,decision:verdict,aligned_count:current.aligned})}
  function share(withResult){if(withResult&&!current)return;const target=withResult?url+'results/'+current.result.slug+'/':url;const quote=withResult?current.result.quote:'Would you date yourself? 8 choices. One match. One honest decision.';track(withResult?'share_result':'share_game',{platform:'facebook',...(withResult?{result_type:current.result.slug,decision:current.verdict}: {})});const shareUrl='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(target)+'&quote='+encodeURIComponent(quote);const popup=window.open('about:blank','_blank');if(popup){popup.opener=null;popup.location.replace(shareUrl)}else window.location.assign(shareUrl)}
  function reset(focus=false){clearTimeout(timer);choices=[];index=0;current=null;profile=null;accepting=true;$('evidence').open=false;show('start');progress(0,'Meet someone with your kind of energy.');if(focus)$('start-button').focus({preventScroll:true})}
  $('start-button').onclick=()=>{if(screen!=='start')return;track('game_start',{question_count:8});question()};
  $('back-button').onclick=()=>{if(screen==='question'&&index>0&&accepting){index--;choices.length=index;question()}};
  $('date-yes').onclick=event=>reveal('yes',event);$('date-no').onclick=event=>reveal('no',event);
  $('restart-button').onclick=()=>{track('replay',{result_type:current?.result.slug});reset(true)};
  $('share-game-button').onclick=()=>share(false);$('share-start-button').onclick=()=>share(false);$('share-result-button').onclick=()=>share(true);
  $('next-game-link').onclick=()=>track('next_game_click',{destination_game_id:'toxic_dating_habit'});
  $('evidence').ontoggle=()=>{document.body.dataset.evidence=$('evidence').open?'open':'closed';if($('evidence').open&&current)track('evidence_view',{result_type:current.result.slug});if(!$('evidence').open&&screen==='result')window.scrollTo({top:0,behavior:'instant'})};
  track('game_view');reset();
})();
