(()=>{
  'use strict';
  const data=DEAL_DATA,$=id=>document.getElementById(id),url='https://hiclassmate.com/games/devils-offer/';
  let screen='start',index=0,choices=[],current=null,reviewIndex=0,lockedUntil=0;
  const track=(name,params={})=>window.hcTrack?.(name,{game_id:data.id,quiz_id:data.id,...params});
  function accept(e){if(e?.detail>1||performance.now()<lockedUntil)return false;lockedUntil=performance.now()+280;return true}
  function show(next,heading){screen=next;document.body.dataset.screen=next;['start','question','arrival','result','review'].forEach(k=>$(k+'-panel').hidden=k!==next);window.scrollTo({top:0,behavior:'instant'});if(heading)$(heading).focus({preventScroll:true})}
  function progress(n,label,count){$('progress-label').textContent=label;$('progress-count').textContent=count;$('progress-bar').style.width=n/8*100+'%';$('progress-track').setAttribute('aria-valuenow',n);$('progress-track').setAttribute('aria-valuetext',label)}
  function question(){const q=data.questions[index];$('question-chapter').textContent=q.chapter;$('question-icon').textContent=q.icon;$('question-scene').textContent=q.scene;$('question-title').textContent=q.question;$('back-button').disabled=index===0;$('battery-count').textContent=(8-index)+' offers left';$('battery-fill').style.width=(8-index)/8*100+'%';
    $('answers').replaceChildren(...q.answers.map((a,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.dataset.choice=i;const letter=Object.assign(document.createElement('span'),{className:'answer-letter',textContent:'AB'[i]});letter.setAttribute('aria-hidden','true');b.append(letter,Object.assign(document.createElement('span'),{textContent:a.text}));b.onclick=e=>{if(screen!=='question'||!accept(e))return;choices[index]=i;track('question_answer',{question_id:q.id,question_number:index+1,answer_choice:'ab'[i]});index++;if(index<8)question();else{current=DealEngine.result(data,choices);progress(8,'The contracts are closed.','8 / 8');show('arrival','arrival-title');track('deals_complete')}};return b}));progress(index,'Read the fine print',(index+1)+' / 8');show('question','question-title')}
  function result(){const r=current.result;document.documentElement.style.setProperty('--result-color',r.color);$('result-symbol').textContent=r.icon;$('result-title').textContent=r.title;$('result-quote').textContent=r.quote;$('result-description').textContent=r.description;$('result-need').textContent=current.need;$('result-nudge').textContent=r.nudge;$('result-count').textContent=current.accepted+' of 8 deals signed';$('result-chips').replaceChildren(...r.chips.map(t=>Object.assign(document.createElement('span'),{textContent:t})));progress(8,'Your temptation. Your limit.','8 / 8');show('result','result-title');if(!current.completed){current.completed=true;track('game_complete',{result_type:r.slug,matching_choices:current.count,tied_results:current.tied.length})}track('result_view',{result_type:r.slug})}
  function review(){const row=current.rows[reviewIndex];$('review-icon').textContent=row.question.icon;$('review-title').textContent=row.question.question;$('review-choice').textContent='You chose: '+row.answer.text;$('review-theme').textContent=row.choice===0?'You accepted: '+data.results[row.question.temptation].chips[0].replace('Devil’s bait: ',''):'You protected: '+data.protections[row.question.protection].title;$('review-reading').textContent=row.answer.reflection;$('review-back').disabled=reviewIndex===0;$('review-next').textContent=reviewIndex===7?'Back to my result →':'Next choice →';progress(reviewIndex+1,'Your choices, reflected back',(reviewIndex+1)+' / 8');show('review','review-title');track('choice_review',{question_number:reviewIndex+1})}
  function share(withResult){if(withResult&&!current)return;const target=withResult?url+'results/'+current.result.slug+'/':url;track(withResult?'share_result':'share_game',{platform:'facebook',...(withResult?{result_type:current.result.slug}:{})});const targetUrl='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(target);const popup=window.open('about:blank','_blank');if(popup){popup.opener=null;popup.location.replace(targetUrl)}else window.location.assign(targetUrl)}
  function reset(focus=false){index=0;reviewIndex=0;choices=[];current=null;lockedUntil=0;progress(0,'Every wish has a price.','8 choices');show('start',focus?'start-title':null)}
  $('start-button').onclick=e=>{if(screen==='start'&&accept(e)){track('game_start',{question_count:8});question()}};
  $('back-button').onclick=e=>{if(screen==='question'&&index>0&&accept(e)){index--;choices.length=index;question()}};
  $('uncover-button').onclick=e=>{if(screen==='arrival'&&accept(e))result()};
  $('review-button').onclick=e=>{if(screen==='result'&&accept(e)){reviewIndex=0;review()}};
  $('review-back').onclick=e=>{if(screen==='review'&&reviewIndex>0&&accept(e)){reviewIndex--;review()}};
  $('review-next').onclick=e=>{if(screen!=='review'||!accept(e))return;if(reviewIndex<7){reviewIndex++;review()}else result()};
  $('review-return').onclick=e=>{if(screen==='review'&&accept(e))result()};
  $('restart-button').onclick=e=>{if(screen==='result'&&accept(e)){track('replay',{result_type:current.result.slug});reset(true)}};
  $('share-game-button').onclick=()=>share(false);$('share-start-button').onclick=()=>share(false);$('share-result-button').onclick=()=>share(true);
  track('game_view');reset();
})();
