const GAME_DATA={results:{main:{title:'Classroom Main Character',emoji:'🌟',description:'You choose the bold story every time. You bring energy, speak up, and somehow turn an ordinary school day into a scene everyone remembers.',traits:['Bold','Expressive','Adventure-ready']},mvp:{title:'Barkada MVP',emoji:'🤝',description:'Your choices keep the whole group together. You value shared wins, good vibes, and making sure nobody feels left out.',traits:['Loyal','Social','Supportive']},chill:{title:'Chill Seatmate',emoji:'😎',description:'You protect your peace and make smart choices without unnecessary drama. Friends can relax around you because your vibe stays steady.',traits:['Calm','Easygoing','Grounded']},wild:{title:'Clever Wildcard',emoji:'🃏',description:'Your answers are hard to predict—and that is exactly the fun. You improvise, notice unusual options, and always have a surprising reason.',traits:['Creative','Flexible','Unexpected']}},questions:[
{text:'On presentation day, would you rather...',a:{text:'Go first and get it over with',scores:{main:2,wild:1}},b:{text:'Go last after watching everyone else',scores:{chill:2,mvp:1}}},
{text:'For a group project, would you rather...',a:{text:'Lead the plan and assign the tasks',scores:{main:2,mvp:1}},b:{text:'Take the weird task nobody else wants',scores:{wild:2,chill:1}}},
{text:'During lunch break, would you rather...',a:{text:'Sit with the biggest, loudest group',scores:{mvp:2,main:1}},b:{text:'Find one seatmate and talk for ages',scores:{chill:2,wild:1}}},
{text:'Would you rather face...',a:{text:'A surprise quiz every Monday',scores:{chill:2,wild:1}},b:{text:'A surprise oral recitation every Friday',scores:{main:2,mvp:1}}},
{text:'For one whole school year, would you rather...',a:{text:'Always have perfect notes',scores:{chill:2,mvp:1}},b:{text:'Always have the funniest comeback',scores:{wild:2,main:1}}},
{text:'At a school event, would you rather...',a:{text:'Perform on stage with your friends',scores:{main:2,mvp:2}},b:{text:'Run a secret snack table backstage',scores:{wild:2,chill:1}}},
{text:'If the teacher leaves for five minutes, would you rather...',a:{text:'Keep everyone quiet and on task',scores:{mvp:2,chill:1}},b:{text:'Start a harmless classroom challenge',scores:{wild:2,main:1}}},
{text:'Would you rather be known as...',a:{text:'The classmate who knows every answer',scores:{main:2,chill:1}},b:{text:'The classmate everyone tells secrets to',scores:{mvp:2,wild:1}}},
{text:'For your seat assignment, would you rather...',a:{text:'Sit in front where everything happens',scores:{main:2,mvp:1}},b:{text:'Sit at the back with the perfect view',scores:{chill:2,wild:1}}},
{text:'On the last day of class, would you rather...',a:{text:'Give everyone a dramatic goodbye speech',scores:{main:2,mvp:1}},b:{text:'Leave a mysterious note in the group chat',scores:{wild:2,chill:1}}}
]};
const el={start:document.querySelector('#start-panel'),question:document.querySelector('#question-panel'),result:document.querySelector('#result-panel'),startButton:document.querySelector('#start-button'),questionText:document.querySelector('#question-text'),a:document.querySelector('#choice-a'),b:document.querySelector('#choice-b'),progressLabel:document.querySelector('#progress-label'),progressCount:document.querySelector('#progress-count'),progressBar:document.querySelector('#progress-bar'),emoji:document.querySelector('#result-emoji'),title:document.querySelector('#result-title'),description:document.querySelector('#result-description'),traits:document.querySelector('#trait-list'),share:document.querySelector('#share-button'),restart:document.querySelector('#restart-button')};
let index=0,scores={},currentResult=null;
function reset(){index=0;scores={main:0,mvp:0,chill:0,wild:0};currentResult=null;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Ready to choose?';el.progressCount.textContent='10 choices';el.progressBar.style.width='0%'}
function start(){el.start.hidden=true;showQuestion()}
function showQuestion(){const q=GAME_DATA.questions[index];el.question.hidden=false;el.questionText.textContent=q.text;el.a.querySelector('strong').textContent=q.a.text;el.b.querySelector('strong').textContent=q.b.text;el.progressLabel.textContent=`Choice ${index+1} of ${GAME_DATA.questions.length}`;el.progressCount.textContent=`${Math.round(index/GAME_DATA.questions.length*100)}% complete`;el.progressBar.style.width=`${index/GAME_DATA.questions.length*100}%`;el.a.onclick=()=>choose(q.a);el.b.onclick=()=>choose(q.b)}
function choose(answer){Object.entries(answer.scores).forEach(([key,value])=>scores[key]+=value);index+=1;if(index===GAME_DATA.questions.length)showResult();else showQuestion()}
function showResult(){const winningKey=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0];currentResult=GAME_DATA.results[winningKey];el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='All choices complete';el.progressCount.textContent='100% complete';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.description.textContent=currentResult.description;el.traits.innerHTML=currentResult.traits.map(trait=>`<span>${trait}</span>`).join('');el.result.scrollIntoView({behavior:'smooth',block:'nearest'})}
function share(){if(!currentResult)return;const url=location.protocol==='http:'||location.protocol==='https:'?location.href.split('?')[0].split('#')[0]:'https://hiclassmate.com/games/would-you-rather/';const quote=`My Classroom Would You Rather type is ${currentResult.title}! Which type are you?`;window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
el.startButton.addEventListener('click',start);el.share.addEventListener('click',share);el.restart.addEventListener('click',()=>{reset();el.start.scrollIntoView({behavior:'smooth',block:'center'})});reset();
