const GAME_DATA={results:{
main:{slug:'main-character',title:'Classroom Main Character',emoji:'🌟',comparison:'bolder',basePercent:84,description:'You treat every school day like the camera is already rolling. Even borrowing a pen somehow becomes a main-character moment.',traits:['Born for the spotlight','First to volunteer','Zero stage fright']},
mvp:{slug:'barkada-mvp',title:'Barkada MVP',emoji:'🤝',comparison:'more team-minded',basePercent:86,description:'You know who needs notes, snacks, and emotional support before they ask. The group project would collapse without you—and everyone knows it.',traits:['Emergency notes provider','Friend-group glue','Always has a plan']},
chill:{slug:'chill-seatmate',title:'Chill Seatmate',emoji:'😎',comparison:'more unbothered',basePercent:82,description:'A surprise quiz, a missing assignment, classroom chaos—you simply adjust your chair and survive. Your stress level is suspiciously low.',traits:['Unbothered legend','Peace protector','Back-row wisdom']},
wild:{slug:'clever-wildcard',title:'Clever Wildcard',emoji:'🃏',comparison:'more unpredictable',basePercent:88,description:'Nobody can predict your answer, including you five seconds earlier. Somehow your strangest ideas keep working.',traits:['Certified plot twist','Creative excuse expert','Chaos with a plan']},
hype:{slug:'hype-captain',title:'The Hype Captain',emoji:'📣',comparison:'more likely to start a classroom movement',basePercent:89,description:'You can turn “Who wants to present?” into a full campaign rally. By lunch, half the class is following a plan you invented ten minutes ago.',traits:['Volume set to 100','Accidental class president','Vibe manager']},
plot:{slug:'plot-twist-student',title:'Plot Twist Student',emoji:'🎭',comparison:'more likely to surprise the whole class',basePercent:91,description:'You look predictable right until you choose the option nobody saw coming. Teachers pause, classmates stare, and you calmly explain the logic.',traits:['Expectation destroyer','Unexpected genius','Never boring']},
groupchat:{slug:'human-group-chat',title:'The Human Group Chat',emoji:'📱',comparison:'more socially essential',basePercent:90,description:'You already know the announcement, the missing homework, and who secretly likes whom. If you are absent, classroom information stops moving.',traits:['Knows everything','Screenshot supplier','Unofficial news desk']},
menace:{slug:'low-key-menace',title:'Low-Key Menace',emoji:'😇',comparison:'more secretly chaotic',basePercent:93,description:'You sit quietly, look innocent, and somehow start the funniest classroom disaster without getting blamed. Honestly, impressive.',traits:['Innocent face','Secret chaos agent','Never gets caught']}
},questions:[
{text:'On presentation day...',a:{text:'Go first and finish fast',scores:{main:2,wild:1}},b:{text:'Go last and watch everyone',scores:{chill:2,mvp:1}}},{text:'For a group project...',a:{text:'Lead and assign the tasks',scores:{main:2,mvp:1}},b:{text:'Take the weirdest task',scores:{wild:2,chill:1}}},{text:'During lunch break...',a:{text:'Join the biggest group',scores:{mvp:2,main:1}},b:{text:'Talk with one seatmate',scores:{chill:2,wild:1}}},{text:'Which surprise is better?',a:{text:'A Monday pop quiz',scores:{chill:2,wild:1}},b:{text:'A Friday oral recitation',scores:{main:2,mvp:1}}},{text:'For the whole school year...',a:{text:'Always have perfect notes',scores:{chill:2,mvp:1}},b:{text:'Always have the best comeback',scores:{wild:2,main:1}}},{text:'At a school event...',a:{text:'Perform with your friends',scores:{main:2,mvp:2}},b:{text:'Run a secret snack table',scores:{wild:2,chill:1}}},{text:'Teacher leaves for 5 minutes...',a:{text:'Keep everyone on task',scores:{mvp:2,chill:1}},b:{text:'Start a harmless challenge',scores:{wild:2,main:1}}},{text:'Would you rather be known as...',a:{text:'The one with every answer',scores:{main:2,chill:1}},b:{text:'The keeper of every secret',scores:{mvp:2,wild:1}}},{text:'Pick your permanent seat...',a:{text:'Front row, center stage',scores:{main:2,mvp:1}},b:{text:'Back row, perfect view',scores:{chill:2,wild:1}}},{text:'On the last day...',a:{text:'Give a dramatic speech',scores:{main:2,mvp:1}},b:{text:'Drop a mysterious group-chat note',scores:{wild:2,chill:1}}}]};
const el={start:document.querySelector('#start-panel'),question:document.querySelector('#question-panel'),result:document.querySelector('#result-panel'),startButton:document.querySelector('#start-button'),questionText:document.querySelector('#question-text'),a:document.querySelector('#choice-a'),b:document.querySelector('#choice-b'),progressLabel:document.querySelector('#progress-label'),progressCount:document.querySelector('#progress-count'),progressBar:document.querySelector('#progress-bar'),emoji:document.querySelector('#result-emoji'),title:document.querySelector('#result-title'),percent:document.querySelector('#result-percent'),description:document.querySelector('#result-description'),traits:document.querySelector('#trait-list'),shareGame:document.querySelector('#share-game-button'),shareResult:document.querySelector('#share-result-button'),restart:document.querySelector('#restart-button')};
let index=0,scores={},currentResult=null,currentPercent=0;const GAME_URL='https://hiclassmate.com/games/would-you-rather/';
function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){index=0;scores={main:0,mvp:0,chill:0,wild:0};currentResult=null;currentPercent=0;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Ready to choose?';el.progressCount.textContent='8 possible types';el.progressBar.style.width='0%'}
function start(){el.start.hidden=true;showQuestion()}function showQuestion(){const q=GAME_DATA.questions[index];el.question.hidden=false;el.questionText.textContent=q.text;el.a.querySelector('strong').textContent=q.a.text;el.b.querySelector('strong').textContent=q.b.text;el.progressLabel.textContent=`Choice ${index+1} of 10`;el.progressCount.textContent=`${index*10}%`;el.progressBar.style.width=`${index*10}%`;el.a.onclick=()=>choose(q.a);el.b.onclick=()=>choose(q.b)}
function choose(answer){Object.entries(answer.scores).forEach(([key,value])=>scores[key]+=value);index+=1;if(index===GAME_DATA.questions.length)showResult();else showQuestion()}
function selectResult(){const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const [first,second]=ranked;const pair=new Set([first[0],second[0]]);let hybrid=null;if(first[1]-second[1]<=3){if(pair.has('main')&&pair.has('mvp'))hybrid='hype';else if(pair.has('main')&&pair.has('wild'))hybrid='plot';else if(pair.has('mvp')&&pair.has('chill'))hybrid='groupchat';else if(pair.has('chill')&&pair.has('wild'))hybrid='menace'}return {result:GAME_DATA.results[hybrid||first[0]],winningScore:first[1]}}
function showResult(){const {result,winningScore}=selectResult();currentResult=result;currentPercent=Math.min(97,currentResult.basePercent+Math.max(0,winningScore-11));el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Result unlocked';el.progressCount.textContent='1 of 8 types';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`You are ${currentResult.comparison} than ${currentPercent}% of classmates`;el.description.textContent=currentResult.description;el.traits.innerHTML=currentResult.traits.map(trait=>`<span>${trait}</span>`).join('')}
function shareGame(){openFacebook(GAME_URL,'Which of 8 ridiculous classmate types are you? Make 10 quick choices to find out!')}function shareResult(){if(!currentResult)return;const resultUrl=`${GAME_URL}results/${currentResult.slug}/?score=${currentPercent}`;openFacebook(resultUrl,`I got ${currentResult.title}! Apparently I am ${currentResult.comparison} than ${currentPercent}% of classmates. What is your result?`)}
el.startButton.addEventListener('click',start);el.shareGame.addEventListener('click',shareGame);el.shareResult.addEventListener('click',shareResult);el.restart.addEventListener('click',reset);reset();
