const GAME_DATA={
  results:{
    taho:{slug:'taho-softie',title:'The Taho Softie',emoji:'🥤',comparison:'warmer before 9 AM',basePercent:91,description:'Gentle, comforting, and always worth waking up for. You check on people quietly and somehow make bad mornings feel softer.',traits:['Soft-hearted','Morning comfort','Low-key sweet'],tag:'Tag the friend who hears the taho vendor before everyone else.'},
    turon:{slug:'turon-crunch',title:'Turon with Main-Character Crunch',emoji:'🍌',comparison:'sweeter with a surprise crunch',basePercent:94,description:'Sweet on the inside, dramatic on the outside. You arrive golden, make an entrance, and leave no boring moment untouched.',traits:['Golden energy','Unexpected crunch','Scene stealer'],tag:'Tag the friend who turns a normal merienda into an event.'},
    halo:{slug:'halo-halo-chaos',title:'The Halo-Halo Chaos Mix',emoji:'🍧',comparison:'more delightfully complicated',basePercent:96,description:'You are twelve moods, three group chats, and one brilliant idea in a single cup. Somehow the mix works—and people always want another scoop.',traits:['Many layers','Colorful chaos','Never boring'],tag:'Tag the friend with more layers than a fully loaded halo-halo.'},
    kwek:{slug:'kwek-kwek-spark',title:'Kwek-Kwek Street Spark',emoji:'🟠',comparison:'bolder with extra sauce',basePercent:95,description:'Bright, fearless, and impossible to ignore. You bring instant energy, defend your opinions, and always know the best street-food spot.',traits:['Bold flavor','Street-smart','Sauce negotiator'],tag:'Tag the friend who orders extra spicy without blinking.'},
    banana:{slug:'banana-cue-classic',title:'The Banana Cue Classic',emoji:'🍢',comparison:'more reliably sweet',basePercent:90,description:'No complicated explanation needed: you are dependable, familiar, and loved by nearly everyone. You always show up when the barkada needs a solid win.',traits:['Classic favorite','Reliable','Sweet but strong'],tag:'Tag the friend everyone automatically saves a seat for.'},
    pandesal:{slug:'pandesal-comfort',title:'Pandesal Comfort Friend',emoji:'🥖',comparison:'more comforting in every situation',basePercent:92,description:'You fit into every plan and make people feel at home. Coffee, cheese, or chismis—you pair well with all of it and never judge the filling.',traits:['Comfort person','Flexible','Always welcome'],tag:'Tag the friend who makes every kwentuhan feel safe.'},
    canton:{slug:'pancit-canton-night-owl',title:'Pancit Canton Night-Owl',emoji:'🍜',comparison:'more powerful after midnight',basePercent:97,description:'Your best ideas appear when everyone should be asleep. You run on late replies, sudden cravings, and “one last episode” energy.',traits:['Midnight chef','Deadline survivor','GC still active'],tag:'Tag the friend who cooks at 1 AM like it is completely normal.'},
    fishball:{slug:'fishball-socialite',title:'Fishball Sauce Socialite',emoji:'🐟',comparison:'better at gathering a crowd',basePercent:93,description:'You turn one quick snack into a full barkada meeting. Friendly, fast-moving, and generous with the sauce—unless someone double-dips.',traits:['Crowd magnet','After-class energy','Sauce expert'],tag:'Tag the friend who knows everyone at the street-food cart.'}
  },
  questions:[
    {text:'Your ideal merienda timing?',a:{text:'Early enough to fix the whole day',scores:{taho:2,pandesal:1}},b:{text:'After class when everybody is free',scores:{fishball:2,kwek:1}}},
    {text:'The barkada cannot choose where to eat.',a:{text:'Suggest the trusted classic',scores:{banana:2,pandesal:1}},b:{text:'Order a little bit of everything',scores:{halo:2,fishball:1}}},
    {text:'Pick your flavor energy.',a:{text:'Sweet, warm, and comforting',scores:{taho:2,banana:1}},b:{text:'Bold, spicy, extra sauce',scores:{kwek:2,fishball:1}}},
    {text:'It is midnight and you are still awake.',a:{text:'Cook pancit canton immediately',scores:{canton:3}},b:{text:'Scroll, laugh, and plan tomorrow’s snack',scores:{halo:2,turon:1}}},
    {text:'A plan suddenly changes.',a:{text:'Okay lang—I work with anything',scores:{pandesal:2,banana:1}},b:{text:'Perfect. More chaos, more fun',scores:{halo:2,turon:1}}},
    {text:'Your entrance at a get-together?',a:{text:'Quiet, then everyone feels better',scores:{taho:2,pandesal:1}},b:{text:'Loud crunch. Main character has arrived',scores:{turon:2,kwek:1}}},
    {text:'Someone says “last piece na.”',a:{text:'Split it fairly with the group',scores:{banana:2,fishball:1}},b:{text:'Too late. I already claimed it',scores:{kwek:2,canton:1}}},
    {text:'Choose your natural habitat.',a:{text:'Busy street-food cart with friends',scores:{fishball:2,turon:1}},b:{text:'Kitchen at 1 AM with the GC online',scores:{canton:2,halo:1}}}
  ]
};
const GAME_URL='https://hiclassmate.com/games/pinoy-merienda/';
const $=selector=>document.querySelector(selector);
const el={start:$('#start-panel'),question:$('#question-panel'),result:$('#result-panel'),startButton:$('#start-button'),shareStart:$('#share-start-button'),questionText:$('#question-text'),a:$('#choice-a'),b:$('#choice-b'),progressLabel:$('#progress-label'),progressCount:$('#progress-count'),progressBar:$('#progress-bar'),emoji:$('#result-emoji'),title:$('#result-title'),percent:$('#result-percent'),description:$('#result-description'),traits:$('#trait-list'),tag:$('#tag-prompt'),shareGame:$('#share-game-button'),shareResult:$('#share-result-button'),restart:$('#restart-button')};
let questionIndex=0,scores={},currentResult=null,resultPercent=0;
function track(eventName,eventParams={}){window.hcTrack?.(eventName,eventParams)}
function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){questionIndex=0;scores=Object.fromEntries(Object.keys(GAME_DATA.results).map(key=>[key,0]));currentResult=null;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Gutom ka na?';el.progressCount.textContent='8 tasty results';el.progressBar.style.width='0%'}
function start(){track('game_start',{question_count:GAME_DATA.questions.length});el.start.hidden=true;showQuestion()}
function showQuestion(){const question=GAME_DATA.questions[questionIndex];el.question.hidden=false;el.questionText.textContent=question.text;el.a.querySelector('strong').textContent=question.a.text;el.b.querySelector('strong').textContent=question.b.text;el.progressLabel.textContent=`Choice ${questionIndex+1} of ${GAME_DATA.questions.length}`;el.progressCount.textContent=`${Math.round(questionIndex/GAME_DATA.questions.length*100)}%`;el.progressBar.style.width=`${questionIndex/GAME_DATA.questions.length*100}%`;el.a.onclick=()=>choose(question.a,'a');el.b.onclick=()=>choose(question.b,'b')}
function choose(answer,choice){track('question_answer',{question_number:questionIndex+1,answer_choice:choice});Object.entries(answer.scores).forEach(([key,points])=>{scores[key]+=points});questionIndex++;questionIndex===GAME_DATA.questions.length?finish():showQuestion()}
function finish(){const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const topScore=ranked[0][1];const tied=ranked.filter(entry=>entry[1]===topScore);currentResult=GAME_DATA.results[tied[Math.floor(Math.random()*tied.length)][0]];resultPercent=Math.min(99,currentResult.basePercent+Math.max(0,topScore-4));el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Merienda served';el.progressCount.textContent='1 of 8 snacks';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`You are ${currentResult.comparison} than ${resultPercent}% of players`;el.description.textContent=currentResult.description;el.traits.replaceChildren(...currentResult.traits.map(trait=>{const chip=document.createElement('span');chip.textContent=trait;return chip}));el.tag.textContent=currentResult.tag;track('game_complete',{result_type:currentResult.slug,result_percent:resultPercent,question_count:GAME_DATA.questions.length});track('result_view',{result_type:currentResult.slug,result_percent:resultPercent})}
function shareGame(){track('share_game',{platform:'facebook'});openFacebook(GAME_URL,"What's your Pinoy merienda personality? Pick 8 choices and serve your result!")}
function shareResult(){if(!currentResult)return;track('share_result',{platform:'facebook',result_type:currentResult.slug,result_percent:resultPercent});openFacebook(`${GAME_URL}results/${currentResult.slug}/?score=${resultPercent}`,`I got ${currentResult.title}! ${currentResult.tag} Anong merienda ka?`)}
el.startButton.onclick=start;el.shareStart.onclick=shareGame;el.shareGame.onclick=shareGame;el.shareResult.onclick=shareResult;el.restart.onclick=()=>{track('replay',{result_type:currentResult?.slug||'unknown'});reset()};reset();
