const GAME_DATA={questions:[
  {clue:'🚐🌈📢',hint:'Classic colorful ride',answers:['Jeepney','School bus','Tricycle'],correct:0},
  {clue:'🧊🍧🌈',hint:'The more ingredients, the better',answers:['Mais con yelo','Halo-halo','Ice candy'],correct:1},
  {clue:'🎤🎶🏠',hint:'Nobody is shy after the first song',answers:['Family videoke','School program','Radio drama'],correct:0},
  {clue:'📦✈️❤️',hint:'Packed with treats and love from abroad',answers:['Online delivery','Pasalubong bag','Balikbayan box'],correct:2},
  {clue:'⛪🌙9️⃣',hint:'Nine early masses before Christmas',answers:['Simbang Gabi','Flores de Mayo','Town fiesta'],correct:0},
  {clue:'🍚♾️❤️',hint:'The unofficial rule at every meal',answers:['Extra sabaw','Rice is life','Dessert first'],correct:1},
  {clue:'🏀🏘️🔥',hint:'Neighborhood pride is on the line',answers:['Palarong Pambansa','Barangay basketball','Mall tournament'],correct:1},
  {clue:'🍢🛣️🌶️',hint:'One stick becomes five very quickly',answers:['Street-food tusok-tusok','Sunday barbecue','Birthday buffet'],correct:0},
  {clue:'🏖️👨‍👩‍👧‍👦🍲',hint:'The whole clan, one beach, too much food',answers:['Family outing','School field trip','Solo vacation'],correct:0},
  {clue:'🎉🍝🐷',hint:'Every table is full and everyone is invited',answers:['Regular dinner','Fiesta handaan','Quick merienda'],correct:1}
],results:[
  {min:10,slug:'emoji-henyo',title:'Certified Pinoy Emoji Henyo',emoji:'🏆',top:1,description:'Perfect score! Your Pinoy radar needs no signal. You decoded every clue before the barkada finished reading it.'},
  {min:8,slug:'decode-master',title:'Pinoy Decode Master',emoji:'🧠',top:8,description:'Almost perfect. Familiar Pinoy clues do not stay mysterious around you for long.'},
  {min:6,slug:'clue-crusher',title:'Barkada Clue Crusher',emoji:'⚡',top:25,description:'Solid decoding skills! You catch the important clues and recover quickly when the emojis get chaotic.'},
  {min:4,slug:'pinoy-radar',title:'Pinoy Radar Explorer',emoji:'📡',top:45,description:'Your radar is working—just with a few loading bars. One more round could change everything.'},
  {min:0,slug:'emoji-trainee',title:'Emoji Trainee, Pinoy Heart',emoji:'😂',top:70,description:'The clues fought back, but your Pinoy heart remains undefeated. Challenge the group chat and demand a rematch.'}
]};
const GAME_URL='https://hiclassmate.com/games/pinoy-emoji-challenge/';
const $=selector=>document.querySelector(selector);const el={start:$('#start-panel'),question:$('#question-panel'),result:$('#result-panel'),startButton:$('#start-button'),shareStart:$('#share-start-button'),shareGame:$('#share-game-button'),clue:$('#emoji-clue'),hint:$('#question-hint'),answers:$('#answer-grid'),feedback:$('#feedback'),progressLabel:$('#progress-label'),scoreLabel:$('#score-label'),progressBar:$('#progress-bar'),resultEmoji:$('#result-emoji'),resultTitle:$('#result-title'),resultRank:$('#result-rank'),resultScore:$('#result-score'),resultTime:$('#result-time'),resultDescription:$('#result-description'),shareResult:$('#share-result-button'),restart:$('#restart-button')};
let index=0,correct=0,startedAt=0,currentResult=null,elapsedSeconds=0,locked=false;
function track(name,params={}){window.hcTrack?.(name,params)}function facebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){index=0;correct=0;startedAt=0;currentResult=null;elapsedSeconds=0;locked=false;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Ready to decode?';el.scoreLabel.textContent='10 clues';el.progressBar.style.width='0%'}
function start(){startedAt=performance.now();track('game_start',{question_count:GAME_DATA.questions.length});el.start.hidden=true;showQuestion()}
function showQuestion(){locked=false;const question=GAME_DATA.questions[index];el.question.hidden=false;el.feedback.textContent='';el.clue.textContent=question.clue;el.hint.textContent=question.hint;el.progressLabel.textContent=`Clue ${index+1} of ${GAME_DATA.questions.length}`;el.scoreLabel.textContent=`${correct} correct`;el.progressBar.style.width=`${index/GAME_DATA.questions.length*100}%`;el.answers.replaceChildren(...question.answers.map((answer,answerIndex)=>{const button=document.createElement('button');button.className='answer-button';button.type='button';button.textContent=answer;button.onclick=()=>choose(button,answerIndex);return button}))}
function choose(button,answerIndex){if(locked)return;locked=true;const question=GAME_DATA.questions[index];const isCorrect=answerIndex===question.correct;if(isCorrect)correct++;[...el.answers.children].forEach((item,itemIndex)=>{item.disabled=true;if(itemIndex===question.correct)item.classList.add('correct');else if(item===button)item.classList.add('wrong')});el.feedback.textContent=isCorrect?'Tama! +1 🎉':`Answer: ${question.answers[question.correct]}`;track('question_answer',{question_number:index+1,answer_choice:answerIndex+1,is_correct:isCorrect});setTimeout(()=>{index++;index===GAME_DATA.questions.length?finish():showQuestion()},520)}
function finish(){elapsedSeconds=Math.max(1,Math.round((performance.now()-startedAt)/1000));currentResult=GAME_DATA.results.find(result=>correct>=result.min);el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Challenge complete';el.scoreLabel.textContent=`${correct}/10`;el.progressBar.style.width='100%';el.resultEmoji.textContent=currentResult.emoji;el.resultTitle.textContent=currentResult.title;el.resultRank.textContent=`You ranked in the top ${currentResult.top}%`;el.resultScore.textContent=`${correct}/10`;el.resultTime.textContent=`${elapsedSeconds}s`;el.resultDescription.textContent=currentResult.description;track('game_complete',{score:correct,max_score:10,time_seconds:elapsedSeconds,result_type:currentResult.slug,top_percent:currentResult.top});track('result_view',{score:correct,result_type:currentResult.slug,top_percent:currentResult.top})}
function shareGame(){track('share_game',{platform:'facebook'});facebook(GAME_URL,'Can you decode all 10 Pinoy emoji clues? Beat my score!')}
function shareResult(){if(!currentResult)return;track('share_result',{platform:'facebook',score:correct,result_type:currentResult.slug,top_percent:currentResult.top});facebook(`${GAME_URL}results/${currentResult.slug}/?score=${correct}&time=${elapsedSeconds}`,`I got ${correct}/10 in ${elapsedSeconds}s and ranked in the top ${currentResult.top}%! Can you beat my Pinoy Emoji score?`)}
el.startButton.onclick=start;el.shareStart.onclick=shareGame;el.shareGame.onclick=shareGame;el.shareResult.onclick=shareResult;el.restart.onclick=()=>{track('replay',{previous_score:correct});reset()};reset();
