(()=>{
  'use strict';
  const data=RIVER_DATA,$=id=>document.getElementById(id),url='https://hiclassmate.com/games/river-within/';
  let screen='start',index=0,revealIndex=0,choices=[],current=null,lockedUntil=0,saving=false;
  const track=(name,details={})=>window.hcTrack?.(name,{game_id:data.id,quiz_id:data.id,...details});
  function accept(event){if(event?.detail>1||performance.now()<lockedUntil)return false;lockedUntil=performance.now()+280;return true}
  function show(next,heading){screen=next;document.body.dataset.screen=next;['start','question','arrival','reveal','result'].forEach(k=>$(k+'-panel').hidden=k!==next);window.scrollTo({top:0,behavior:'instant'});if(heading)$(heading).focus({preventScroll:true})}
  function progress(value,label,count){$('progress-label').textContent=label;$('progress-count').textContent=count;$('progress-bar').style.width=value/6*100+'%';$('progress-track').setAttribute('aria-valuenow',value);$('progress-track').setAttribute('aria-valuetext',label)}
  function question(){const s=data.scenes[index];$('question-chapter').textContent=s.chapter;$('question-animal').textContent=s.icon;$('question-scene').textContent=s.scene;$('question-title').textContent=s.question;$('back-button').disabled=index===0;
    $('answers').replaceChildren(...s.answers.map((a,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.dataset.choice=i;const letter=Object.assign(document.createElement('span'),{className:'answer-letter',textContent:'AB'[i]});letter.setAttribute('aria-hidden','true');b.append(letter,Object.assign(document.createElement('span'),{textContent:a.text}));b.onclick=e=>{if(screen!=='question'||!accept(e))return;choices[index]=i;track('question_answer',{question_number:index+1,question_id:s.id,answer_choice:'ab'[i]});index++;if(index<data.scenes.length)question();else{current=RiverEngine.result(data,choices);progress(6,'The far bank','6 / 6');show('arrival','arrival-title');track('crossing_complete')}};return b}));progress(index,'The crossing',(index+1)+' / 6');show('question','question-title')}
  function reveal(){const {scene:s,answer:a}=current.rows[revealIndex];$('reveal-animal').textContent=s.icon;$('reveal-name').textContent=s.animal+' represents';$('reveal-title').textContent=s.symbol;$('reveal-meaning').textContent=s.meaning;$('reveal-choice').textContent='You chose: '+a.text;$('reveal-label').textContent=a.label;$('reveal-reading').textContent=a.reading;$('reveal-nudge').textContent=a.nudge;$('reveal-back').disabled=revealIndex===0;$('reveal-next').textContent=revealIndex===5?'See my river portrait →':'Meet the next meaning →';progress(revealIndex+1,'Behind your choices',(revealIndex+1)+' / 6');show('reveal','reveal-title');track('symbol_reveal',{symbol_id:s.id,answer_choice:'ab'[choices[revealIndex]]})}
  function result(){const r=current.result;document.documentElement.style.setProperty('--result-color',r.color);$('result-title').textContent=r.title;$('result-quote').textContent=r.quote;$('result-description').textContent=r.description;$('result-reminder').textContent=r.reminder;$('result-chips').replaceChildren(...r.chips.map(t=>Object.assign(document.createElement('span'),{textContent:t})));$('save-status').textContent='';progress(6,'Your river portrait','6 / 6');show('result','result-title');track('result_view',{result_type:r.slug})}
  function share(withResult){if(withResult&&!current)return;const target=withResult?url+'results/'+current.result.slug+'/':url;track(withResult?'share_result':'share_game',{platform:'facebook',...(withResult?{result_type:current.result.slug}:{})});const shareUrl='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(target);const popup=window.open('about:blank','_blank');if(popup){popup.opener=null;popup.location.replace(shareUrl)}else window.location.assign(shareUrl)}
  function reset(focus=false){choices=[];index=0;revealIndex=0;current=null;lockedUntil=0;progress(0,'A little journey inward','6 choices');show('start',focus?'start-title':null)}
  function wrap(ctx,text,x,y,width,line){let words=text.split(' '),row='';for(const word of words){const test=row?row+' '+word:word;if(ctx.measureText(test).width>width&&row){ctx.fillText(row,x,y);y+=line;row=word}else row=test}if(row)ctx.fillText(row,x,y);return y+line}
  async function save(){if(saving||!current)return;saving=true;const snapshot=current;$('save-button').disabled=true;$('save-status').textContent='Preparing your keepsake…';try{
    const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1720;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.fillStyle='#fffdf5';ctx.fillRect(0,0,1080,1720);
    const art=new Image();art.src='river-art.jpg';await art.decode();const scale=Math.max(1080/art.width,400/art.height);ctx.save();ctx.beginPath();ctx.rect(0,0,1080,400);ctx.clip();ctx.drawImage(art,(1080-art.width*scale)/2,(400-art.height*scale)/2,art.width*scale,art.height*scale);ctx.restore();
    ctx.fillStyle='#285c49';ctx.font='700 21px Arial';ctx.fillText('HI CLASSMATE  /  THE RIVER WITHIN',60,445);ctx.font='52px Georgia';ctx.fillText(snapshot.result.title,60,514);ctx.fillStyle='#52675a';ctx.font='25px Arial';wrap(ctx,snapshot.result.quote,60,563,960,34);
    snapshot.rows.forEach(({scene:s,answer:a},i)=>{const y=625+i*151;ctx.fillStyle=i%2?'#f1f3e6':'#e9efdf';ctx.fillRect(40,y,1000,136);ctx.fillStyle='#285c49';ctx.font='700 21px Arial';ctx.fillText(s.animal.toUpperCase()+'  /  '+s.symbol.toUpperCase(),60,y+30);ctx.fillStyle='#34493c';ctx.font='23px Arial';wrap(ctx,'You chose: '+a.text,60,y+65,950,29);ctx.font='italic 23px Georgia';wrap(ctx,a.short,60,y+102,950,28)});
    ctx.fillStyle='#66766d';ctx.font='22px Arial';ctx.fillText('Six choices. Six story symbols. What will your crossing reveal?',60,1600);ctx.font='700 23px Arial';ctx.fillText('hiclassmate.com/games/river-within/',60,1650);
    const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image unavailable')),'image/png'));const link=document.createElement('a'),objectUrl=URL.createObjectURL(blob);link.href=objectUrl;link.download='my-river-'+snapshot.result.slug+'.png';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),30000);if(current===snapshot)$('save-status').textContent='Your keepsake is ready to save.';track('save_result',{result_type:snapshot.result.slug});
  }catch{if(current===snapshot)$('save-status').textContent='Could not save the image. Please try again.'}finally{saving=false;$('save-button').disabled=false}}
  $('start-button').onclick=e=>{if(screen!=='start'||!accept(e))return;track('game_start',{question_count:6});question()};
  $('back-button').onclick=e=>{if(screen==='question'&&index>0&&accept(e)){index--;choices.length=index;question()}};
  $('uncover-button').onclick=e=>{if(screen==='arrival'&&accept(e)){revealIndex=0;reveal()}};
  $('reveal-back').onclick=e=>{if(screen==='reveal'&&revealIndex>0&&accept(e)){revealIndex--;reveal()}};
  $('reveal-next').onclick=e=>{if(screen!=='reveal'||!accept(e))return;if(revealIndex<5){revealIndex++;reveal()}else{if(!current.completed){track('game_complete',{result_type:current.result.slug});current.completed=true}result()}};
  $('review-button').onclick=e=>{if(screen==='result'&&accept(e)){revealIndex=0;reveal()}};
  $('restart-button').onclick=e=>{if(screen==='result'&&accept(e)){track('replay',{result_type:current.result.slug});reset(true)}};
  $('share-game-button').onclick=()=>share(false);$('share-start-button').onclick=()=>share(false);$('share-result-button').onclick=()=>share(true);$('save-button').onclick=save;
  track('game_view');reset();
})();
