const gameConfig={rounds:5,waitRangeMs:[1400,3800],results:[{max:190,title:"Lightning Legend",description:"That was seriously fast! You react before most classmates have even realized what happened. Your focus and timing are a powerful combo."},{max:230,title:"Quick-Draw Classmate",description:"Sharp eyes, quick hands. You're the classmate who catches the falling pen before it hits the floor."},{max:280,title:"Locked-In Seatmate",description:"You stay alert and respond with confidence. A solid reaction time like this is perfect for friendly classroom challenges."},{max:340,title:"Steady Responder",description:"Calm and dependable wins plenty of races. You don't rush—you wait for the real signal and make your move."},{max:Infinity,title:"Chill Reactor",description:"You're not letting a flashing screen boss you around. Try once more when you're rested, focused, and ready to surprise the barkada."}]};
const elements={pad:document.querySelector("#reaction-pad"),icon:document.querySelector("#pad-icon"),status:document.querySelector("#game-status"),help:document.querySelector("#pad-help"),round:document.querySelector("#round-label"),score:document.querySelector("#score-label"),primary:document.querySelector("#primary-button"),resultPanel:document.querySelector("#result-panel"),average:document.querySelector("#average-score"),fastest:document.querySelector("#fastest-score"),rounds:document.querySelector("#round-scores"),resultTitle:document.querySelector("#result-title"),resultDescription:document.querySelector("#result-description"),share:document.querySelector("#share-button"),restart:document.querySelector("#restart-button")};
let phase="ready",scores=[],waitTimer=null,signalTime=0,currentResult=null;
function randomWait(){const[min,max]=gameConfig.waitRangeMs;return Math.floor(Math.random()*(max-min+1))+min}function setPad(state,icon,title,help){elements.pad.className=`reaction-pad is-${state}`;elements.icon.textContent=icon;elements.status.textContent=title;elements.help.textContent=help}
function resetGame(){clearTimeout(waitTimer);phase="ready";scores=[];currentResult=null;elements.round.textContent="Ready to play?";elements.score.textContent=`${gameConfig.rounds} rounds`;elements.primary.textContent="Start the test";elements.primary.hidden=false;elements.resultPanel.hidden=true;setPad("ready","⚡","Test your reflexes","Tap start, then wait for green.")}
function beginRound(){clearTimeout(waitTimer);phase="waiting";const roundNumber=scores.length+1;elements.round.textContent=`Round ${roundNumber} of ${gameConfig.rounds}`;elements.score.textContent=scores.length?`Last: ${scores.at(-1)} ms`:"Stay focused";elements.primary.hidden=true;setPad("waiting","✋","Wait for green...","Don't tap yet!");waitTimer=window.setTimeout(()=>{phase="go";signalTime=performance.now();setPad("go","⚡","TAP NOW!","As fast as you can!")},randomWait())}
function handlePadTap(){if(phase==="waiting"){clearTimeout(waitTimer);phase="false";setPad("false","😅","Too soon!","Wait for green. This round won't count.");elements.primary.textContent="Retry this round";elements.primary.hidden=false;return}if(phase!=="go")return;const reaction=Math.max(1,Math.round(performance.now()-signalTime));scores.push(reaction);phase="hit";setPad("hit","🎯",`${reaction} ms`,scores.length===gameConfig.rounds?"Test complete!":"Nice tap!");elements.score.textContent=`Best: ${Math.min(...scores)} ms`;if(scores.length===gameConfig.rounds){window.setTimeout(showResult,500)}else{elements.primary.textContent="Next round";elements.primary.hidden=false}}
function showResult(){phase="complete";const average=Math.round(scores.reduce((sum,score)=>sum+score,0)/scores.length);currentResult=gameConfig.results.find(result=>average<result.max);elements.average.textContent=average;elements.fastest.textContent=`${Math.min(...scores)} ms`;elements.rounds.textContent=scores.map(score=>`${score} ms`).join(" · ");elements.resultTitle.textContent=currentResult.title;elements.resultDescription.textContent=currentResult.description;elements.round.textContent="All 5 rounds complete";elements.score.textContent=`${average} ms average`;elements.primary.hidden=true;elements.resultPanel.hidden=false;elements.resultPanel.scrollIntoView({behavior:"smooth",block:"nearest"})}
function shareResult(){if(!currentResult)return;const average=Math.round(scores.reduce((sum,score)=>sum+score,0)/scores.length);const pageUrl=location.protocol==="http:"||location.protocol==="https:"?location.href.split("?")[0].split("#")[0]:"https://hiclassmate.com/games/reaction-speed/";const quote=`My classroom reaction time is ${average} ms — I'm a ${currentResult.title}! How fast are you?`;const shareUrl=`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(pageUrl)}&quote=${encodeURIComponent(quote)}`;window.open(shareUrl,"facebook-share","width=640,height=720,noopener,noreferrer")}
elements.primary.addEventListener("click",beginRound);elements.pad.addEventListener("click",handlePadTap);elements.restart.addEventListener("click",()=>{resetGame();elements.pad.scrollIntoView({behavior:"smooth",block:"center"})});elements.share.addEventListener("click",shareResult);resetGame();
