(()=>{
  'use strict';
  const data=HOUSE_DATA,$=id=>document.getElementById(id),url='https://hiclassmate.com/games/house-in-the-woods/';
  let screen='start',index=0,revealIndex=0,choices=[],current=null,lockedUntil=0;
  const track=(name,details={})=>window.hcTrack?.(name,{game_id:data.id,quiz_id:data.id,...details});
  function accept(event){if(event?.detail>1||performance.now()<lockedUntil)return false;lockedUntil=performance.now()+280;return true}
  function show(next,heading){screen=next;document.body.dataset.screen=next;['start','question','arrival','reveal','result'].forEach(k=>$(k+'-panel').hidden=k!==next);window.scrollTo({top:0,behavior:'instant'});if(heading)$(heading).focus({preventScroll:true})}
  function progress(value,label,count){$('progress-label').textContent=label;$('progress-count').textContent=count;$('progress-bar').style.width=value/6*100+'%';$('progress-track').setAttribute('aria-valuenow',value);$('progress-track').setAttribute('aria-valuetext',label)}
  function question(){const s=data.scenes[index];$('question-chapter').textContent=s.chapter;$('question-animal').textContent=s.icon;$('question-scene').textContent=s.scene;$('question-title').textContent=s.question;$('back-button').disabled=index===0;
    $('answers').replaceChildren(...s.answers.map((a,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.dataset.choice=i;const letter=Object.assign(document.createElement('span'),{className:'answer-letter',textContent:'AB'[i]});letter.setAttribute('aria-hidden','true');b.append(letter,Object.assign(document.createElement('span'),{textContent:a.text}));b.onclick=e=>{if(screen!=='question'||!accept(e))return;choices[index]=i;track('question_answer',{question_number:index+1,question_id:s.id,answer_choice:'ab'[i]});index++;if(index<data.scenes.length)question();else{current=HouseEngine.result(data,choices);progress(6,'The last page','6 / 6');show('arrival','arrival-title');track('story_complete')}};return b}));progress(index,'Inside the house',(index+1)+' / 6');show('question','question-title')}
  function reveal(){const {scene:s,answer:a}=current.rows[revealIndex];$('reveal-animal').textContent=s.icon;$('reveal-name').textContent=s.animal+' represents';$('reveal-title').textContent=s.symbol;$('reveal-meaning').textContent=s.meaning;$('reveal-choice').textContent='You chose: '+a.text;$('reveal-label').textContent=a.label;$('reveal-reading').textContent=a.reading;$('reveal-nudge').textContent=a.nudge;$('reveal-back').disabled=revealIndex===0;$('reveal-next').textContent=revealIndex===5?'See my full result →':'Next hidden meaning →';progress(revealIndex+1,'Behind your choices',(revealIndex+1)+' / 6');show('reveal','reveal-title');track('symbol_reveal',{symbol_id:s.id,answer_choice:'ab'[choices[revealIndex]]})}
  function result(){const r=current.result;$('result-symbol').textContent=r.icon;document.documentElement.style.setProperty('--result-color',r.color);$('result-title').textContent=r.title;$('result-quote').textContent=r.quote;$('result-description').textContent=r.description;$('result-reminder').textContent=r.reminder;$('result-chips').replaceChildren(...r.chips.map(t=>Object.assign(document.createElement('span'),{textContent:t})));progress(6,'Your house personality','6 / 6');show('result','result-title');track('result_view',{result_type:r.slug})}
  function share(withResult){if(withResult&&!current)return;const target=withResult?url+'results/'+current.result.slug+'/':url;track(withResult?'share_result':'share_game',{platform:'facebook',...(withResult?{result_type:current.result.slug}:{})});const shareUrl='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(target);const popup=window.open('about:blank','_blank');if(popup){popup.opener=null;popup.location.replace(shareUrl)}else window.location.assign(shareUrl)}
  function reset(focus=false){choices=[];index=0;revealIndex=0;current=null;lockedUntil=0;progress(0,'A house full of hidden meanings','6 choices');show('start',focus?'start-title':null)}
  $('start-button').onclick=e=>{if(screen!=='start'||!accept(e))return;track('game_start',{question_count:6});question()};
  $('back-button').onclick=e=>{if(screen==='question'&&index>0&&accept(e)){index--;choices.length=index;question()}};
  $('uncover-button').onclick=e=>{if(screen==='arrival'&&accept(e)){revealIndex=0;reveal()}};
  $('reveal-back').onclick=e=>{if(screen==='reveal'&&revealIndex>0&&accept(e)){revealIndex--;reveal()}};
  $('reveal-next').onclick=e=>{if(screen!=='reveal'||!accept(e))return;if(revealIndex<5){revealIndex++;reveal()}else{if(!current.completed){track('game_complete',{result_type:current.result.slug});current.completed=true}result()}};
  $('review-button').onclick=e=>{if(screen==='result'&&accept(e)){revealIndex=0;reveal()}};
  $('restart-button').onclick=e=>{if(screen==='result'&&accept(e)){track('replay',{result_type:current.result.slug});reset(true)}};
  $('share-game-button').onclick=()=>share(false);$('share-start-button').onclick=()=>share(false);$('share-result-button').onclick=()=>share(true);
  track('game_view');reset();
})();
