const HOUSE_DATA = {
  id:'house_in_the_woods', title:'The House in the Woods',
  scenes:[
    {id:'door',animal:'The front door',icon:'🚪',chapter:'01 · The doorstep',scene:'On a walk through the woods, you find a little house with a light on inside.',question:'What do you do first?',symbol:'Meeting someone new',meaning:'In this story, the front door represents your first step toward a new connection.',axis:'openness',answers:[
      {text:'Knock on the door.',value:1,label:'You give connection a chance',short:'You let people know you are there.',reading:'You chose to knock. When someone catches your interest, you may prefer a small, clear gesture over waiting to be noticed. You do not need the whole story before saying hello.',nudge:'An open invitation still leaves room to see how the other person responds.'},
      {text:'Look through the window first.',value:0,label:'You take in the details first',short:'You like a little context before stepping closer.',reading:'You chose to look first. You may feel more comfortable getting a sense of someone before showing your interest. Noticing the atmosphere helps you decide how much of yourself to bring forward.',nudge:'Sometimes a simple hello tells you more than watching from a distance.'}
    ]},
    {id:'invitation',animal:'The invitation',icon:'💬',chapter:'02 · A voice inside',scene:'The door opens. A friendly voice says, “Come in, there is room for you.”',question:'How do you respond?',symbol:'How you build trust',meaning:'The invitation represents what helps you feel comfortable accepting someone’s welcome.',axis:'openness',answers:[
      {text:'Step in and say hello.',value:1,label:'You start with a little trust',short:'You are willing to meet warmth with warmth.',reading:'You chose to step inside. You may give a new connection some room to unfold before needing every question answered. A welcoming gesture makes it easier for you to offer one back.',nudge:'You can stay curious and still change your mind as you learn more.'},
      {text:'Ask who is there first.',value:0,label:'Clarity helps you relax',short:'You open up more easily when you know where you stand.',reading:'You chose to ask a question. You may enjoy a welcome more when it comes with a little clarity. Understanding who you are meeting helps you choose how close you want to be.',nudge:'A question can build a bridge; it does not have to become a test.'}
    ]},
    {id:'cups',animal:'The two cups',icon:'☕',chapter:'03 · A place at the table',scene:'Inside, two cups sit on a small table. One chair has been pulled out for you.',question:'What catches your attention?',symbol:'What you look for in belonging',meaning:'The two cups represent what makes a shared space feel meaningful to you.',axis:'discovery',answers:[
      {text:'A place to sit. I take the chair.',value:0,label:'You notice the welcome',short:'A simple place beside someone can be enough.',reading:'You chose the waiting chair. You may be drawn to the feeling of being included without needing a big explanation. Small, ordinary gestures can make a place feel like yours.',nudge:'You are allowed to ask for more than a seat when something matters to you.'},
      {text:'Who is the other cup waiting for?',value:1,label:'You notice the story',short:'You want to know the person behind the gesture.',reading:'You wondered about the other cup. You may feel connected when you understand the stories around you. Who was expected, what came before, and what happens next all add meaning.',nudge:'Let a moment be good even when part of its story is still unknown.'}
    ]},
    {id:'music',animal:'The locked room',icon:'🗝️',chapter:'04 · A hidden melody',scene:'A soft melody comes from a locked room. The host says you may ask about anything in the house.',question:'What do you choose?',symbol:'Your private curiosity',meaning:'The locked room represents a part of life you are curious about but have not explored yet.',axis:'discovery',answers:[
      {text:'Ask the host to open the room.',value:1,label:'You want to find out for yourself',short:'Curiosity turns into a question you actually ask.',reading:'You chose to ask about the room. When something draws you in, you may want an experience of your own rather than a guess from the outside. Wonder often becomes a first step for you.',nudge:'An unanswered question can stay interesting without needing an immediate answer.'},
      {text:'Stay outside and enjoy the music.',value:0,label:'You can enjoy an unfinished mystery',short:'You do not need to uncover everything to appreciate it.',reading:'You chose to listen. You may find meaning in what a moment gives you right now, without needing to go further. Some things can feel more spacious when they are left partly unexplained.',nudge:'If you truly want to know, you are allowed to ask.'}
    ]},
    {id:'gift',animal:'The little box',icon:'🎁',chapter:'05 · Something for you',scene:'Before you leave, the host offers you a small wrapped box. “This is yours,” they say.',question:'When will you open it?',symbol:'How you receive affection',meaning:'The gift represents how you make room for a gesture meant just for you.',axis:'openness',answers:[
      {text:'Open it now, with the host.',value:1,label:'You like to share the happy moment',short:'Your reaction becomes part of the gift.',reading:'You chose to open it together. You may enjoy letting someone see what their gesture means to you. Sharing the surprise can feel as important as whatever is inside.',nudge:'You do not have to perform a perfect reaction for your gratitude to be real.'},
      {text:'Thank them and open it alone later.',value:0,label:'You feel it before you show it',short:'Private joy is still joy.',reading:'You chose a moment alone. You may like to discover your own response before anyone else’s expectations enter the picture. A quiet reaction can hold just as much warmth as an excited one.',nudge:'A small message later can help someone see the appreciation you felt.'}
    ]},
    {id:'rain',animal:'The rain',icon:'🌧️',chapter:'06 · Time to go',scene:'A light, warm rain starts as you reach the door. The host invites you to stay; your path home is familiar.',question:'How does your visit end?',symbol:'Comfort and moving forward',meaning:'The rain represents a small interruption between where you are and where you planned to go.',axis:'discovery',answers:[
      {text:'Stay a little longer and watch the rain.',value:0,label:'You let a good moment last',short:'A pause can be part of the journey.',reading:'You chose to stay. When plans shift gently, you may be happy to settle into what is already good. You do not always need the next chapter to begin right away.',nudge:'Check whether you are staying because you want to, or because leaving feels awkward.'},
      {text:'Say goodbye and walk into the drizzle.',value:1,label:'You are ready for your next chapter',short:'A little uncertainty does not have to stop you.',reading:'You chose to go. You may enjoy a connection and still feel ready to move on with your own day. An imperfect moment can be a good enough time to begin.',nudge:'Taking your own path does not mean you have to rush the goodbye.'}
    ]}
  ],
  results:{
    'open-settle':{slug:'open-door',title:'The Open Door',icon:'🚪',color:'#174baf',chips:['Warm welcome','Simple comforts'],quote:'You make a small moment feel like an invitation to stay.',description:'Your choices leaned toward sharing your reactions and enjoying the moment in front of you. You may connect through warmth that feels easy to join.',reminder:'Leave room for your own preferences, too. Being welcoming does not mean always saying yes.'},
    'private-settle':{slug:'quiet-observer',title:'The Quiet Observer',icon:'☕',color:'#5a4ba2',chips:['Thoughtful pace','Quiet appreciation'],quote:'You notice what a moment means before deciding what to share.',description:'Your choices leaned toward opening up at your own pace and appreciating what is already there. You may feel a lot without needing to make it loud.',reminder:'Let a little of that inner world be seen when you want someone to know you.'},
    'open-explore':{slug:'secret-room-explorer',title:'The Secret-Room Explorer',icon:'🗝️',color:'#ae5327',chips:['Open curiosity','Shared discoveries'],quote:'You knock, ask, and turn a little curiosity into a new story.',description:'Your choices leaned toward reaching out and discovering what comes next. You may build connections by sharing both your interest and your reactions.',reminder:'Give people and moments time to unfold, even when you want to know more.'},
    'private-explore':{slug:'own-path-traveler',title:'The Own-Path Traveler',icon:'🧭',color:'#256b70',chips:['Independent rhythm','A curious mind'],quote:'You follow your curiosity without handing over your whole inner world.',description:'Your choices leaned toward exploring while keeping some experiences private. You may enjoy new possibilities most when you can choose your own pace.',reminder:'A little explanation can help someone understand that independence is not indifference.'}
  }
};
if(typeof module!=='undefined')module.exports=HOUSE_DATA;
