const GAME_DATA={
 results:{
  reply:{slug:'reply-reassurance',title:'Reply Reassurance Royalty',emoji:'💬',comparison:'more calming in the chat',basePercent:91,description:'Your replies are emotional seatbelts. A quick update, a clear goodnight, and one sincere “I’m here” are how you make someone feel chosen.',traits:['Consistent replies','Clear reassurance','No mind games'],tag:'Tag the person who notices when your reply time changes by two minutes.'},
  time:{slug:'quality-time-collector',title:'Quality Time Collector',emoji:'⏳',comparison:'more present in the moment',basePercent:92,description:'You do not need a grand plan. Give you an unhurried walk, real kwentuhan, and phones face-down—your full attention is the gift.',traits:['Present energy','Kwentuhan lover','Plans real time'],tag:'Tag the person you can talk to until the guard starts closing the place.'},
  care:{slug:'acts-of-care-mvp',title:'Acts of Care MVP',emoji:'🫶',comparison:'better at quietly saving the day',basePercent:94,description:'You fix the tiny problem before anyone asks. Charger? Umbrella? Notes they missed? Your love language arrives prepared and acts casual about it.',traits:['Quiet helper','Always prepared','Reliable care'],tag:'Tag the person who carries everything except their own problems.'},
  tease:{slug:'lambing-through-teasing',title:'Lambing Through Teasing',emoji:'😜',comparison:'more fluent in playful lambing',basePercent:96,description:'Your affection wears a disguise made of memes, inside jokes, and gentle asar. If you suddenly stop teasing someone, that is when they should worry.',traits:['Meme sender','Inside-joke expert','Soft behind the asar'],tag:'Tag the person you roast daily but would defend in 0.2 seconds.'},
  food:{slug:'kain-tayo-love',title:'“Kain Tayo” Love Language',emoji:'🍟',comparison:'more likely to feed a feeling',basePercent:95,description:'You remember the exact snack order and appear with food at the right moment. For you, “kumain ka na?” is practically a confession.',traits:['Snack remembers','Food = feelings','Shares the last bite'],tag:'Tag the person who says “I’m not hungry” then steals your fries.'},
  music:{slug:'playlist-confession',title:'Playlist Confession Artist',emoji:'🎧',comparison:'more likely to hide feelings in a song',basePercent:93,description:'Why write one risky paragraph when track number four says everything? Your playlists carry clues, moods, and suspiciously specific lyrics.',traits:['Song-message expert','Mood curator','Subtle confession'],tag:'Tag the person whose playlist title is definitely not “random.”'},
  detail:{slug:'tiny-detail-gifter',title:'Tiny Detail Gift-Giver',emoji:'🎁',comparison:'more observant about little things',basePercent:90,description:'You remember what they mentioned once three months ago. The gift may be small, but the “wait—you remembered?” reaction is your real masterpiece.',traits:['Detail detective','Thoughtful surprises','Receipts remembered'],tag:'Tag the person who remembers your favorite everything.'},
  home:{slug:'message-me-home',title:'“Message Me When You’re Home” Energy',emoji:'☂️',comparison:'more protective without making noise',basePercent:97,description:'You care like a soft safety net: checking the route, staying awake, and waiting for the magic word “home.” Protective, never performative.',traits:['Safe-trip checker','Stays awake','Quiet protector'],tag:'Tag the person who will not sleep until everyone says “nakauwi na.”'}
 },
 questions:[
  {text:'They had a terrible day. Your first move?',a:{text:'Send the exact reassuring words they need',scores:{reply:2,time:1}},b:{text:'Bring their favorite snack without asking',scores:{food:2,care:1}}},
  {text:'They are replying slower than usual.',a:{text:'Ask gently if everything is okay',scores:{reply:2,home:1}},b:{text:'Give space, then plan real time together',scores:{time:2,care:1}}},
  {text:'Pick your ideal low-key date.',a:{text:'A long walk with nonstop kwentuhan',scores:{time:2,home:1}},b:{text:'Shared earphones and a made-for-us playlist',scores:{music:2,detail:1}}},
  {text:'How does your flirting usually escape?',a:{text:'Memes, inside jokes, and playful asar',scores:{tease:3}},b:{text:'Remember one tiny detail and surprise them',scores:{detail:2,music:1}}},
  {text:'They are traveling home late.',a:{text:'Wait for the “nakauwi na” message',scores:{home:2,reply:1}},b:{text:'Stay on the call until they get there',scores:{time:2,home:1}}},
  {text:'A small win deserves what?',a:{text:'Their favorite food, obviously',scores:{food:2,care:1}},b:{text:'A tiny gift connected to an old story',scores:{detail:2,music:1}}},
  {text:'After a little tampuhan, you…',a:{text:'Send a clear message: we are okay',scores:{reply:2,tease:1}},b:{text:'Fix something helpful and bring food',scores:{care:2,food:1}}},
  {text:'You are both busy all week. You show care by…',a:{text:'Protecting one real block of quality time',scores:{time:2,music:1}},b:{text:'Sending quick updates, jokes, and check-ins',scores:{reply:1,tease:1,home:1}}}
 ]
};
const GAME_URL='https://hiclassmate.com/games/hidden-love-language/';
const $=selector=>document.querySelector(selector);const el={start:$('#start-panel'),question:$('#question-panel'),result:$('#result-panel'),startButton:$('#start-button'),shareStart:$('#share-start-button'),questionText:$('#question-text'),a:$('#choice-a'),b:$('#choice-b'),progressLabel:$('#progress-label'),progressCount:$('#progress-count'),progressBar:$('#progress-bar'),emoji:$('#result-emoji'),title:$('#result-title'),percent:$('#result-percent'),description:$('#result-description'),traits:$('#trait-list'),tag:$('#tag-prompt'),shareGame:$('#share-game-button'),shareResult:$('#share-result-button'),restart:$('#restart-button')};let questionIndex=0,scores={},currentResult=null,resultPercent=0;
function track(eventName,eventParams={}){window.hcTrack?.(eventName,eventParams)}function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){questionIndex=0;scores=Object.fromEntries(Object.keys(GAME_DATA.results).map(key=>[key,0]));currentResult=null;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Ready for kilig?';el.progressCount.textContent='8 secret signals';el.progressBar.style.width='0%'}
function start(){track('game_start',{question_count:GAME_DATA.questions.length});el.start.hidden=true;showQuestion()}function showQuestion(){const question=GAME_DATA.questions[questionIndex];el.question.hidden=false;el.questionText.textContent=question.text;el.a.querySelector('strong').textContent=question.a.text;el.b.querySelector('strong').textContent=question.b.text;el.progressLabel.textContent=`Choice ${questionIndex+1} of ${GAME_DATA.questions.length}`;el.progressCount.textContent=`${Math.round(questionIndex/GAME_DATA.questions.length*100)}%`;el.progressBar.style.width=`${questionIndex/GAME_DATA.questions.length*100}%`;el.a.onclick=()=>choose(question.a,'a');el.b.onclick=()=>choose(question.b,'b')}
function choose(answer,choice){track('question_answer',{question_number:questionIndex+1,answer_choice:choice});Object.entries(answer.scores).forEach(([key,points])=>{scores[key]+=points});questionIndex++;questionIndex===GAME_DATA.questions.length?finish():showQuestion()}
function finish(){const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const topScore=ranked[0][1];const tied=ranked.filter(entry=>entry[1]===topScore);currentResult=GAME_DATA.results[tied[Math.floor(Math.random()*tied.length)][0]];resultPercent=Math.min(99,currentResult.basePercent+Math.max(0,topScore-4));el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Secret signal revealed';el.progressCount.textContent='1 of 8 styles';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`You are ${currentResult.comparison} than ${resultPercent}% of players`;el.description.textContent=currentResult.description;el.traits.replaceChildren(...currentResult.traits.map(trait=>{const chip=document.createElement('span');chip.textContent=trait;return chip}));el.tag.textContent=currentResult.tag;track('game_complete',{result_type:currentResult.slug,result_percent:resultPercent,question_count:GAME_DATA.questions.length});track('result_view',{result_type:currentResult.slug,result_percent:resultPercent})}
function shareGame(){track('share_game',{platform:'facebook'});openFacebook(GAME_URL,"What's your hidden love language? Pick 8 kilig choices and reveal your secret signal!")}function shareResult(){if(!currentResult)return;track('share_result',{platform:'facebook',result_type:currentResult.slug,result_percent:resultPercent});openFacebook(`${GAME_URL}results/${currentResult.slug}/?score=${resultPercent}`,`I got ${currentResult.title}! What's your hidden love language?`)}
el.startButton.onclick=start;el.shareStart.onclick=shareGame;el.shareGame.onclick=shareGame;el.shareResult.onclick=shareResult;el.restart.onclick=()=>{track('replay',{result_type:currentResult?.slug||'unknown'});reset()};reset();
