const GAME_DATA={results:{
family:{slug:'titas-favorite',title:"Tita's Favorite",emoji:'💖',comparison:'more reunion-ready',basePercent:84,description:'You greet every relative, accept the second serving, and somehow leave with three containers of food. The titas already approved you.',traits:['Mano po expert','Always says salamat','Take-home container magnet']},
barkada:{slug:'barkada-representative',title:'Barkada Representative',emoji:'🫶',comparison:'more barkada-powered',basePercent:87,description:'You make the plan, revive the group chat, and make sure nobody gets left behind. Walang iwanan—even when everyone is late.',traits:['GC revival specialist','Friend-group glue','Always game']},
diskarte:{slug:'jeepney-survival-expert',title:'Jeepney Survival Expert',emoji:'🚌',comparison:'more street-smart',basePercent:89,description:'Exact fare, perfect timing, and a sixth sense for the last available seat. Metro Manila rush hour trained you well.',traits:['Bayad po champion','Commute strategist','May paraan palagi']},
food:{slug:'sari-sari-vip',title:'Sari-Sari Store VIP',emoji:'🍬',comparison:'more merienda-motivated',basePercent:85,description:'The tindera knows your usual snack before you say it. You believe every serious problem deserves a quick merienda first.',traits:['Tingi snack expert','Merienda defender','May sukli pa']},
karaoke:{slug:'karaoke-main-character',title:'Karaoke Main Character',emoji:'🎤',comparison:'more videoke-ready',basePercent:92,description:'You say “last song na” and add three more. The opening notes play and suddenly the family reunion is your concert.',traits:['Mic never returned','Power-ballad energy','Applause expected']},
core:{slug:'certified-pinoy-core',title:'Certified Pinoy Core',emoji:'☀️',comparison:'more Pinoy-coded',basePercent:94,description:'You can pass jeepney fare, organize the barkada, and find food for everyone—all while checking if classes are suspended.',traits:['Maximum diskarte','Bayanihan instinct','Ready for anything']},
fiesta:{slug:'fiesta-plate-champion',title:'Fiesta Plate Champion',emoji:'🍽️',comparison:'more handaan-ready',basePercent:91,description:'Your plate has pancit, lumpia, rice, spaghetti, and somehow dessert still fits. This is not overeating; this is strategy.',traits:['Buffet route planner','Second-round specialist','Dessert has separate space']},
pasalubong:{slug:'pasalubong-guardian',title:'Pasalubong Guardian',emoji:'🎁',comparison:'more family-first',basePercent:90,description:'You protect the snacks until everyone gets home—even when one pack is calling your name. Self-control worthy of a medal.',traits:['Snack security','Family-first energy','Counts every piece']}
},questions:[
{text:'One seat opens in a crowded jeepney...',a:{text:'Siksik pa—make room for one more',scores:{barkada:2,diskarte:1}},b:{text:'Guard the seat like a commuter pro',scores:{diskarte:2,food:1}}},
{text:'There is one last piece of fried chicken...',a:{text:'Ask “wala nang may gusto?” twice',scores:{family:2,food:1}},b:{text:'Take it before the question starts',scores:{food:2,diskarte:1}}},
{text:'The videoke microphone reaches you...',a:{text:'Pick the biggest power ballad',scores:{barkada:2,family:1}},b:{text:'Pass it—but sing every backup line',scores:{family:2,food:1}}},
{text:'Heavy rain starts before class...',a:{text:'Refresh the suspension announcement nonstop',scores:{diskarte:2,barkada:1}},b:{text:'The bag is packed, but hope is alive',scores:{family:1,food:2}}},
{text:'Someone comes home with pasalubong...',a:{text:'Wait until everybody is complete',scores:{family:2,barkada:1}},b:{text:'Taste-test one piece for quality',scores:{food:2,diskarte:1}}},
{text:'Your barkada cannot choose where to eat...',a:{text:'Send one final plan with a meeting time',scores:{barkada:2,diskarte:1}},b:{text:'Say “kahit saan” until someone decides',scores:{food:2,family:1}}},
{text:'At the sari-sari store...',a:{text:'Buy your exact favorite tingi snack',scores:{food:2,diskarte:1}},b:{text:'Add something for the friend beside you',scores:{barkada:2,family:1}}},
{text:'A family reunion group photo begins...',a:{text:'Call everyone and arrange the rows',scores:{family:2,barkada:1}},b:{text:'Appear at the back at the perfect second',scores:{diskarte:2,food:1}}},
{text:'The meetup is at 3:00 PM...',a:{text:'Arrive early and send “nandito na ako”',scores:{family:2,diskarte:1}},b:{text:'Still choosing an outfit at 2:55',scores:{barkada:2,food:1}}},
{text:'The food table opens at a birthday party...',a:{text:'Make plates for the younger cousins first',scores:{family:2,barkada:1}},b:{text:'Build the perfect pancit-lumpia combo',scores:{food:2,diskarte:1}}}]};
const el={start:document.querySelector('#start-panel'),question:document.querySelector('#question-panel'),result:document.querySelector('#result-panel'),startButton:document.querySelector('#start-button'),questionText:document.querySelector('#question-text'),a:document.querySelector('#choice-a'),b:document.querySelector('#choice-b'),progressLabel:document.querySelector('#progress-label'),progressCount:document.querySelector('#progress-count'),progressBar:document.querySelector('#progress-bar'),emoji:document.querySelector('#result-emoji'),title:document.querySelector('#result-title'),percent:document.querySelector('#result-percent'),description:document.querySelector('#result-description'),traits:document.querySelector('#trait-list'),shareGame:document.querySelector('#share-game-button'),shareResult:document.querySelector('#share-result-button'),restart:document.querySelector('#restart-button')};
let index=0,scores={},currentResult=null,currentPercent=0;const GAME_URL='https://hiclassmate.com/games/how-pinoy-are-you/';
function openFacebook(url,quote){window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(quote)}`,'facebook-share','width=640,height=720,noopener,noreferrer')}
function reset(){index=0;scores={family:0,barkada:0,diskarte:0,food:0};currentResult=null;currentPercent=0;el.start.hidden=false;el.question.hidden=true;el.result.hidden=true;el.progressLabel.textContent='Handa ka na?';el.progressCount.textContent='8 possible results';el.progressBar.style.width='0%'}
function start(){el.start.hidden=true;showQuestion()}function showQuestion(){const q=GAME_DATA.questions[index];el.question.hidden=false;el.questionText.textContent=q.text;el.a.querySelector('strong').textContent=q.a.text;el.b.querySelector('strong').textContent=q.b.text;el.progressLabel.textContent=`Tanong ${index+1} of 10`;el.progressCount.textContent=`${index*10}%`;el.progressBar.style.width=`${index*10}%`;el.a.onclick=()=>choose(q.a);el.b.onclick=()=>choose(q.b)}
function choose(answer){Object.entries(answer.scores).forEach(([key,value])=>scores[key]+=value);index+=1;if(index===GAME_DATA.questions.length)showResult();else showQuestion()}
function selectResult(){const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const [first,second]=ranked;const pair=new Set([first[0],second[0]]);let hybrid=null;if(first[1]-second[1]<=3){if(pair.has('family')&&pair.has('barkada'))hybrid='karaoke';else if(pair.has('barkada')&&pair.has('diskarte'))hybrid='core';else if(pair.has('barkada')&&pair.has('food'))hybrid='fiesta';else if(pair.has('family')&&pair.has('food'))hybrid='pasalubong'}return {result:GAME_DATA.results[hybrid||first[0]],winningScore:first[1]}}
function showResult(){const {result,winningScore}=selectResult();currentResult=result;currentPercent=Math.min(98,currentResult.basePercent+Math.max(0,winningScore-11));el.question.hidden=true;el.result.hidden=false;el.progressLabel.textContent='Result unlocked';el.progressCount.textContent='1 of 8 types';el.progressBar.style.width='100%';el.emoji.textContent=currentResult.emoji;el.title.textContent=currentResult.title;el.percent.textContent=`You are ${currentResult.comparison} than ${currentPercent}% of players`;el.description.textContent=currentResult.description;el.traits.innerHTML=currentResult.traits.map(trait=>`<span>${trait}</span>`).join('')}
function shareGame(){openFacebook(GAME_URL,'How Pinoy are you? Make 10 everyday choices and discover your very Pinoy result!')}function shareResult(){if(!currentResult)return;const resultUrl=`${GAME_URL}results/${currentResult.slug}/?score=${currentPercent}&card=1`;openFacebook(resultUrl,`I got ${currentResult.title}! Apparently I am ${currentResult.comparison} than ${currentPercent}% of players. Ikaw, ano ang result mo?`)}
el.startButton.addEventListener('click',start);el.shareGame.addEventListener('click',shareGame);el.shareResult.addEventListener('click',shareResult);el.restart.addEventListener('click',reset);reset();
